// Numbers, measure words, dates, and times — practice reference data.
// Numbers carry an optional example_en; measures pair a classifier with an example.
window.MP_NUMBERS = {
  numbers: [
    { zh: '零', pinyin: 'líng', en: '0' },
    { zh: '一', pinyin: 'yī', en: '1' },
    { zh: '二', pinyin: 'èr', en: '2' },
    { zh: '三', pinyin: 'sān', en: '3' },
    { zh: '四', pinyin: 'sì', en: '4' },
    { zh: '五', pinyin: 'wǔ', en: '5' },
    { zh: '六', pinyin: 'liù', en: '6' },
    { zh: '七', pinyin: 'qī', en: '7' },
    { zh: '八', pinyin: 'bā', en: '8' },
    { zh: '九', pinyin: 'jiǔ', en: '9' },
    { zh: '十', pinyin: 'shí', en: '10' },
    { zh: '十一', pinyin: 'shí yī', en: '11' },
    { zh: '十二', pinyin: 'shí èr', en: '12' },
    { zh: '十三', pinyin: 'shí sān', en: '13' },
    { zh: '十四', pinyin: 'shí sì', en: '14' },
    { zh: '十五', pinyin: 'shí wǔ', en: '15' },
    { zh: '十六', pinyin: 'shí liù', en: '16' },
    { zh: '十七', pinyin: 'shí qī', en: '17' },
    { zh: '十八', pinyin: 'shí bā', en: '18' },
    { zh: '十九', pinyin: 'shí jiǔ', en: '19' },
    { zh: '二十', pinyin: 'èr shí', en: '20' },
    { zh: '二十一', pinyin: 'èr shí yī', en: '21' },
    { zh: '二十二', pinyin: 'èr shí èr', en: '22' },
    { zh: '二十三', pinyin: 'èr shí sān', en: '23' },
    { zh: '二十四', pinyin: 'èr shí sì', en: '24' },
    { zh: '二十五', pinyin: 'èr shí wǔ', en: '25' },
    { zh: '二十六', pinyin: 'èr shí liù', en: '26' },
    { zh: '二十七', pinyin: 'èr shí qī', en: '27' },
    { zh: '二十八', pinyin: 'èr shí bā', en: '28' },
    { zh: '二十九', pinyin: 'èr shí jiǔ', en: '29' },
    { zh: '三十', pinyin: 'sān shí', en: '30' },
    { zh: '三十一', pinyin: 'sān shí yī', en: '31' },
    { zh: '三十二', pinyin: 'sān shí èr', en: '32' },
    { zh: '三十三', pinyin: 'sān shí sān', en: '33' },
    { zh: '三十四', pinyin: 'sān shí sì', en: '34' },
    { zh: '三十五', pinyin: 'sān shí wǔ', en: '35' },
    { zh: '三十六', pinyin: 'sān shí liù', en: '36' },
    { zh: '三十七', pinyin: 'sān shí qī', en: '37' },
    { zh: '三十八', pinyin: 'sān shí bā', en: '38' },
    { zh: '三十九', pinyin: 'sān shí jiǔ', en: '39' },
    { zh: '四十', pinyin: 'sì shí', en: '40' },
    { zh: '四十一', pinyin: 'sì shí yī', en: '41' },
    { zh: '四十二', pinyin: 'sì shí èr', en: '42' },
    { zh: '四十三', pinyin: 'sì shí sān', en: '43' },
    { zh: '四十四', pinyin: 'sì shí sì', en: '44' },
    { zh: '四十五', pinyin: 'sì shí wǔ', en: '45' },
    { zh: '四十六', pinyin: 'sì shí liù', en: '46' },
    { zh: '四十七', pinyin: 'sì shí qī', en: '47' },
    { zh: '四十八', pinyin: 'sì shí bā', en: '48' },
    { zh: '四十九', pinyin: 'sì shí jiǔ', en: '49' },
    { zh: '五十', pinyin: 'wǔ shí', en: '50' },
    { zh: '五十一', pinyin: 'wǔ shí yī', en: '51' },
    { zh: '五十二', pinyin: 'wǔ shí èr', en: '52' },
    { zh: '五十三', pinyin: 'wǔ shí sān', en: '53' },
    { zh: '五十四', pinyin: 'wǔ shí sì', en: '54' },
    { zh: '五十五', pinyin: 'wǔ shí wǔ', en: '55' },
    { zh: '五十六', pinyin: 'wǔ shí liù', en: '56' },
    { zh: '五十七', pinyin: 'wǔ shí qī', en: '57' },
    { zh: '五十八', pinyin: 'wǔ shí bā', en: '58' },
    { zh: '五十九', pinyin: 'wǔ shí jiǔ', en: '59' },
    { zh: '六十', pinyin: 'liù shí', en: '60' },
    { zh: '六十一', pinyin: 'liù shí yī', en: '61' },
    { zh: '六十二', pinyin: 'liù shí èr', en: '62' },
    { zh: '六十三', pinyin: 'liù shí sān', en: '63' },
    { zh: '六十四', pinyin: 'liù shí sì', en: '64' },
    { zh: '六十五', pinyin: 'liù shí wǔ', en: '65' },
    { zh: '六十六', pinyin: 'liù shí liù', en: '66' },
    { zh: '六十七', pinyin: 'liù shí qī', en: '67' },
    { zh: '六十八', pinyin: 'liù shí bā', en: '68' },
    { zh: '六十九', pinyin: 'liù shí jiǔ', en: '69' },
    { zh: '七十', pinyin: 'qī shí', en: '70' },
    { zh: '七十一', pinyin: 'qī shí yī', en: '71' },
    { zh: '七十二', pinyin: 'qī shí èr', en: '72' },
    { zh: '七十三', pinyin: 'qī shí sān', en: '73' },
    { zh: '七十四', pinyin: 'qī shí sì', en: '74' },
    { zh: '七十五', pinyin: 'qī shí wǔ', en: '75' },
    { zh: '七十六', pinyin: 'qī shí liù', en: '76' },
    { zh: '七十七', pinyin: 'qī shí qī', en: '77' },
    { zh: '七十八', pinyin: 'qī shí bā', en: '78' },
    { zh: '七十九', pinyin: 'qī shí jiǔ', en: '79' },
    { zh: '八十', pinyin: 'bā shí', en: '80' },
    { zh: '八十一', pinyin: 'bā shí yī', en: '81' },
    { zh: '八十二', pinyin: 'bā shí èr', en: '82' },
    { zh: '八十三', pinyin: 'bā shí sān', en: '83' },
    { zh: '八十四', pinyin: 'bā shí sì', en: '84' },
    { zh: '八十五', pinyin: 'bā shí wǔ', en: '85' },
    { zh: '八十六', pinyin: 'bā shí liù', en: '86' },
    { zh: '八十七', pinyin: 'bā shí qī', en: '87' },
    { zh: '八十八', pinyin: 'bā shí bā', en: '88' },
    { zh: '八十九', pinyin: 'bā shí jiǔ', en: '89' },
    { zh: '九十', pinyin: 'jiǔ shí', en: '90' },
    { zh: '九十一', pinyin: 'jiǔ shí yī', en: '91' },
    { zh: '九十二', pinyin: 'jiǔ shí èr', en: '92' },
    { zh: '九十三', pinyin: 'jiǔ shí sān', en: '93' },
    { zh: '九十四', pinyin: 'jiǔ shí sì', en: '94' },
    { zh: '九十五', pinyin: 'jiǔ shí wǔ', en: '95' },
    { zh: '九十六', pinyin: 'jiǔ shí liù', en: '96' },
    { zh: '九十七', pinyin: 'jiǔ shí qī', en: '97' },
    { zh: '九十八', pinyin: 'jiǔ shí bā', en: '98' },
    { zh: '九十九', pinyin: 'jiǔ shí jiǔ', en: '99' },
    { zh: '一百', pinyin: 'yī bǐi', en: '100' },
    { zh: '一千', pinyin: 'yī qiān', en: 'one thousand' },
    { zh: '一万', pinyin: 'yī wàn', en: 'ten thousand' },
    { zh: '一半', pinyin: 'yī bàn', en: 'half / one half', example_en: 'Only half the class showed up.' },
    { zh: '两三个', pinyin: 'liǎng sān ge', en: 'two or three; a couple of', example_zh: '我要两三个苹果。', example_pinyin: 'Wǒ yào liǎng sān ge píngguǒ', example_en: 'two or three; a couple of' },
    { zh: '俩', pinyin: 'liǎ', en: 'two (colloquial pair)', example_zh: '他们俩是好朋友。', example_pinyin: 'Tāmen liǎ shì hǎo péngyou', example_en: 'two (colloquial pair)' },
    { zh: '一对', pinyin: 'yì duì', en: 'a pair', example_zh: '这是一对夫妻。', example_pinyin: 'Zhè shì yí duì fūqī', example_en: 'a pair' },
    { zh: '十几个', pinyin: 'shí jǐ ge', en: 'a dozen or so; a teeny number', example_zh: '来了十几个客人。', example_pinyin: 'Lái le shí jǐ ge kèrén', example_en: 'a dozen or so; a teeny number' },
    { zh: '几十个', pinyin: 'jǐ shí ge', en: 'dozens; several tens of', example_zh: '几十个人就坐满了。', example_pinyin: 'Jǐ shí ge rén jiù zuò mǎn le', example_en: 'dozens; several tens of' },
    { zh: '几百个', pinyin: 'jǐ bǎi ge', en: 'hundreds of', example_zh: '几百个人在等他。', example_pinyin: 'Jǐ bǎi ge rén zài děng tā', example_en: 'hundreds of' },
    { zh: '成百上千', pinyin: 'chéng bǎi shàng qiān', en: 'hundreds and thousands', example_zh: '来学中文的人成百上千。', example_pinyin: 'Lái xué Zhōngwén de rén chéng bǎi qiān wàn', example_en: 'hundreds and thousands' },
    { zh: '一个半', pinyin: 'yí ge bàn', en: 'one and a half', example_zh: '我吃了一个半包子。', example_pinyin: 'Wǒ chī le yí gè bàn bāozi', example_en: 'one and a half' },
    { zh: '两个半', pinyin: 'liǎng ge bàn', en: 'two and a half', example_zh: '孩子两岁半了。', example_pinyin: 'Háizi liǎng suì bàn le', example_en: 'two and a half' },
    { zh: '十来个', pinyin: 'shí lái ge', en: 'about ten; ten-ish', example_zh: '十来个分钟就够了。', example_pinyin: 'Shí lái ge fēnzhōng jiù gòu le', example_en: 'about ten; ten-ish' },
    { zh: '成双成对', pinyin: 'chéng shuāng chéng duì', en: 'in pairs', example_zh: '他们成双成对地走着。', example_pinyin: 'Tāmen chéng shuāng chéng duì de zǒu zhe', example_en: 'in pairs' },
    { zh: '三五成群', pinyin: 'sān wǔ chéng qún', en: 'in small groups', example_zh: '同学们三五成群地聊天。', example_pinyin: 'Tóngxuéshì sān wǔ chéng qún de liáo tiān', example_en: 'in small groups' },
    { zh: '千千万万', pinyin: 'qiān qiān wàn wàn', en: 'countless', example_zh: '秋天的落叶千千万万。', example_pinyin: 'Qiūtiān de luòyè qiān qiān wàn wàn', example_en: 'countless' },
    { zh: '零零碎碎', pinyin: 'líng líng suì suì', en: 'scattered bits and pieces', example_zh: '桌上放着零零碎碎的东西。', example_pinyin: 'Zhuō shàng fàng zhe líng líng suì suì de dōngxi', example_en: 'scattered bits and pieces' },
    { zh: '大大小小', pinyin: 'dà dà xiǎo xiǎo', en: 'big and small of all sizes', example_zh: '大大小小有二十个盒子。', example_pinyin: 'Dà dà xiǎo xiǎo yǒu èrshí ge hézi', example_en: 'big and small of all sizes' },
    { zh: '一共', pinyin: 'yí gòng', en: 'altogether; in total', example_zh: '一共多少钱？', example_pinyin: 'Yìgòng duōshao qián?', example_en: 'altogether; in total' },
    { zh: '两', pinyin: 'liǎng', en: 'two (counted nouns)', example_zh: '我有两本书。', example_pinyin: 'Wǒ yǒu liǎng běn shū', example_en: 'two (counted nouns)' },
  ],
  measures: [
    { zh: '个', pinyin: 'gè', en: 'general classifier — the default for most nouns', kind: 'general classifier — the default for most nouns', example_zh: '三个苹果', example_pinyin: 'sān ge píngguǒ', example_en: 'three apples', note: 'Use 个 whenever you have no better classifier. Note 個/个 is written 个.' },
    { zh: '本', pinyin: 'běn', en: 'books, notebooks, dictionaries — anything with pages', kind: 'books, notebooks, dictionaries — anything with pages', example_zh: '两本书', example_pinyin: 'liǎng běn shū', example_en: 'two books', note: 'Often shortened to 本 in speech.' },
    { zh: '张', pinyin: 'zhāng', en: 'flat paper-like things: tickets, photos, beds, tables', kind: 'flat paper-like things: tickets, photos, beds, tables', example_zh: '一张照片', example_pinyin: 'yì zhāng zhàopiàn', example_en: 'one photo', note: '张 is counted, not 张儿.' },
    { zh: '只', pinyin: 'zhī', en: 'one of a pair, and animals: birds, dogs, pens', kind: 'one of a pair, and animals: birds, dogs, pens', example_zh: '一只狗', example_pinyin: 'yì zhī gǒu', example_en: 'one dog', note: '只 is also the measure for single objects like a pen or a shoe.' },
    { zh: '条', pinyin: 'tiáo', en: 'long, thin, strip-like things: fish, streets, towels, news', kind: 'long, thin, strip-like things: fish, streets, towels, news', example_zh: '一条鱼', example_pinyin: 'yì tiáo yú', example_en: 'one fish', note: 'Also used for rivers, roads, and 条消息 (a piece of news).' },
    { zh: '杯', pinyin: 'bēi', en: 'cups and glasses of anything', kind: 'cups and glasses of anything', example_zh: '一杯水', example_pinyin: 'yì bēi shuǐ', example_en: 'a glass of water', note: '杯 doubles as the noun \'cup\'.' },
    { zh: '碗', pinyin: 'wǎn', en: 'bowls of food or soup', kind: 'bowls of food or soup', example_zh: '一碗面', example_pinyin: 'yì wǎn miàn', example_en: 'a bowl of noodles', note: '碗 is also the bowl itself.' },
    { zh: '双', pinyin: 'shuāng', en: 'things that come in pairs: shoes, socks, hands, eyes', kind: 'things that come in pairs: shoes, socks, hands, eyes', example_zh: '一双鞋', example_pinyin: 'yì shuāng xié', example_en: 'a pair of shoes', note: 'Natural for anything paired on the body.' },
    { zh: '件', pinyin: 'jiàn', en: 'clothing and individual items/events', kind: 'clothing and individual items/events', example_zh: '一件衣服', example_pinyin: 'yì jiàn yīfu', example_en: 'one piece of clothing', note: '件 covers garments, matters (件事), and 件 in emails.' },
    { zh: '片', pinyin: 'piàn', en: 'flat slices or small irregular pieces: bread, meat, film', kind: 'flat slices or small irregular pieces: bread, meat, film', example_zh: '一片面包', example_pinyin: 'yì piàn miànbāo', example_en: 'a slice of bread', note: '片 also counts films and short messages (a piece).' },
    { zh: '块', pinyin: 'kuài', en: 'square chunks, money, abstract units', kind: 'square chunks, money, abstract units', example_zh: '一块钱', example_pinyin: 'yì kuài qián', example_en: 'one yuan', note: '块 is a set phrase for money: 两块钱 = two yuan.' },
    { zh: '元', pinyin: 'yuán', en: 'currency: yuan / dollars', kind: 'currency: yuan / dollars', example_zh: '五元', example_pinyin: 'wǔ yuán', example_en: 'five yuan', note: '元 is used for prices and costs; 块 is more casual.' },
    { zh: '把', pinyin: 'bǎ', en: 'things with a handle, plus abstract and casual counts', kind: 'things with a handle, plus abstract and casual counts', example_zh: '一把伞', example_pinyin: 'yì bǎ sǎn', example_en: 'one umbrella', note: '把 is also the disyllabic 把 \'handle\' and the 把 construction.' },
    { zh: '台', pinyin: 'tái', en: 'machines and appliances: TVs, computers, phones', kind: 'machines and appliances: TVs, computers, phones', example_zh: '一台电脑', example_pinyin: 'yì tái diànnǎo', example_en: 'one computer', note: '台 classifies machines and set-top objects.' },
    { zh: '部', pinyin: 'bù', en: 'large machines, vehicles, works, and novels', kind: 'large machines, vehicles, works, and novels', example_zh: '一部手机', example_pinyin: 'yì bù shǒujī', example_en: 'one mobile phone', note: '部 also counts movies and books (部作品).' },
    { zh: '家', pinyin: 'jiā', en: 'households, shops, companies, and (in zhāng) a paper sheet', kind: 'households, shops, companies, and (in zhāng) a paper sheet', example_zh: '一家超市', example_pinyin: 'yì jiā chāoshì', example_en: 'one supermarket', note: '家 shifts in meaning with the noun; 张一家 = one sheet.' },
    { zh: '位', pinyin: 'wèi', en: 'polite classifier for people, especially guests and elders', kind: 'polite classifier for people, especially guests and elders', example_zh: '一位老师', example_pinyin: 'yì wèi lǎoshī', example_en: 'a teacher (polite)', note: 'Use 位 for people you respect; 个 is neutral, 伙 is casual.' },
    { zh: '名', pinyin: 'míng', en: 'people in formal or written contexts (employees, students)', kind: 'people in formal or written contexts (employees, students)', example_zh: '三名学生', example_pinyin: 'sān míng xuéshēng', example_en: 'three students', note: '名 is more written/formal than 个 for people.' },
    { zh: '次', pinyin: 'cì', en: 'occurrences or events, with verbs', kind: 'occurrences or events, with verbs', example_zh: '一次', example_pinyin: 'yì cì', example_en: 'once', note: '次 counts events: 我去过三次 = I have gone three times.' },
    { zh: '顿', pinyin: 'dùn', en: 'meals or blows, as in a beat/punch', kind: 'meals or blows, as in a beat/punch', example_zh: '一顿饭', example_pinyin: 'yì dùn fàn', example_en: 'a meal', note: '顿 counts meals: 吃了两顿饭; also 打断一下.' },
    { zh: '群', pinyin: 'qún', en: 'groups of people or animals', kind: 'groups of people or animals', example_zh: '一群朋友', example_pinyin: 'yì qún péngyou', example_en: 'a group of friends', note: '群 often carries \'a group of\' with a collective feel.' },
    { zh: '根', pinyin: 'gēn', en: 'long thin objects with a base: sticks, cigarettes, lines', kind: 'long thin objects with a base: sticks, cigarettes, lines', example_zh: '一根铅笔', example_pinyin: 'yì gēn qiān bǐ', example_en: 'one pencil', note: '根 counts rods, poles, and counterfactual lines (一根线).' },
    { zh: '支', pinyin: 'zhī', en: 'pen-like instruments and teams', kind: 'pen-like instruments and teams', example_zh: '一支笔', example_pinyin: 'yì zhī bǐ', example_en: 'one pen', note: '支 is standard for 笔, 歌 (a song), and 军队 (a division).' },
    { zh: '辆', pinyin: 'liàng', en: 'vehicles: cars, bikes, buses', kind: 'vehicles: cars, bikes, buses', example_zh: '一辆车', example_pinyin: 'yì liàng chē', example_en: 'one car', note: '辆 is the default vehicle classifier.' },
    { zh: '棵', pinyin: 'kē', en: 'trees and large plants', kind: 'trees and large plants', example_zh: '一棵树', example_pinyin: 'yì kē shù', example_en: 'one tree', note: '棵 grows from the ground; 盆 is for potted plants.' },
    { zh: '朵', pinyin: 'duǒ', en: 'flowers and clouds', kind: 'flowers and clouds', example_zh: '一朵花', example_pinyin: 'yì duǒ huā', example_en: 'one flower', note: '朵 counts blossoming things and cloud puffs.' },
    { zh: '匹', pinyin: 'pǐ', en: 'cloth, bolts of fabric, horses', kind: 'cloth, bolts of fabric, horses', example_zh: '一匹马', example_pinyin: 'yì pǐ mǎ', example_en: 'one horse', note: '匹 is the classifier for horses, masts, and bolts of cloth.' },
    { zh: '座', pinyin: 'zuò', en: 'buildings, mountains, large seats', kind: 'buildings, mountains, large seats', example_zh: '一座桥', example_pinyin: 'yì zuò qiáo', example_en: 'one bridge', note: '座 counts things you sit on or monumental structures.' },
  ],
  dates: [
    { zh: '星期一', pinyin: 'xīng qī yī', en: 'Monday', note: 'Written with 数字 1-7 in speech: 星期一 or 礼拜一.' },
    { zh: '星期二', pinyin: 'xīng qī èr', en: 'Tuesday', note: 'Formal written form of the second day.' },
    { zh: '星期三', pinyin: 'xīng qī sān', en: 'Wednesday', note: 'The only day whose English name is not a person.' },
    { zh: '星期四', pinyin: 'xīng qī sì', en: 'Thursday', note: 'Also 星期四 = 礼拜四.' },
    { zh: '星期五', pinyin: 'xīng qī wǔ', en: 'Friday', note: 'The start of the weekend in Chinese culture.' },
    { zh: '星期六', pinyin: 'xīng qī liù', en: 'Saturday', note: 'Weekend day; also called 周六.' },
    { zh: '星期日', pinyin: 'xīng qī rì', en: 'Sunday', note: '星期天 xīng qī tiān is equally common and more colloquial.' },
    { zh: '星期天', pinyin: 'xīng qī tiān', en: 'Sunday', note: 'Colloquial Sunday, written with 天 not 日.' },
    { zh: '周一', pinyin: 'zhōu yī', en: 'Mon (abbrev.)', note: 'Everyday written abbreviation; 周 = week.' },
    { zh: '周二', pinyin: 'zhōu èr', en: 'Tue (abbrev.)', note: 'Written on calendars as 周二.' },
    { zh: '周三', pinyin: 'zhōu sān', en: 'Wed (abbrev.)', note: 'Also 礼拜三 in spoken style.' },
    { zh: '周四', pinyin: 'zhōu sì', en: 'Thu (abbrev.)', note: 'Formal schedules prefer 周四.' },
    { zh: '周五', pinyin: 'zhōu wǔ', en: 'Fri (abbrev.)', note: 'Often heard as 星期五 in schools.' },
    { zh: '周六', pinyin: 'zhōu liù', en: 'Sat (abbrev.)', note: 'Weekend shorthand: 周末 = the weekend.' },
    { zh: '周日', pinyin: 'zhōu rì', en: 'Sun (abbrev.)', note: 'Note 周日 contrasts with 星期日 but means the same.' },
    { zh: '周末', pinyin: 'zhōu mò', en: 'the weekend', note: '周 + 末 \'end of week\'; 周末愉快 = have a good weekend.' },
    { zh: '一月', pinyin: 'yī yuè', en: 'January', note: 'Month names use 月 \'moon\'; 1st month = 一月.' },
    { zh: '二月', pinyin: 'èr yuè', en: 'February', note: 'The shortest month, 二月.' },
    { zh: '三月', pinyin: 'sān yuè', en: 'March', note: 'Spring in the Northern Hemisphere.' },
    { zh: '四月', pinyin: 'sì yuè', en: 'April', note: '春 season; 清明 often in April.' },
    { zh: '五月', pinyin: 'wǔ yuè', en: 'May', note: 'Includes 劳动节 (Labour Day) around May 1.' },
    { zh: '六月', pinyin: 'liù yuè', en: 'June', note: '初夏 begins; 高考 gaokao happens here.' },
    { zh: '七月', pinyin: 'qī yuè', en: 'July', note: 'Hottest month in much of China.' },
    { zh: '八月', pinyin: 'bā yuè', en: 'August', note: 'Includes the Qixi festival and summer holidays.' },
    { zh: '九月', pinyin: 'jiǔ yuè', en: 'September', note: 'School year starts in September.' },
    { zh: '十月', pinyin: 'shí yuè', en: 'October', note: 'Includes National Day 国庆节 on October 1.' },
    { zh: '十一月', pinyin: 'shí yī yuè', en: 'November', note: 'Read shíyīyuè, often written 11月.' },
    { zh: '十二月', pinyin: 'shí èr yuè', en: 'December', note: 'Includes Christmas and the New Year period.' },
    { zh: '一号', pinyin: 'yī hào', en: 'the 1st (of a month)', note: 'Dates use 号 \'number\' for the day; 一号 = the first.' },
    { zh: '今天', pinyin: 'jīn tiān', en: 'today', note: '今天 + time: 今天早上 = this morning.' },
    { zh: '明天', pinyin: 'míng tiān', en: 'tomorrow', note: 'Also used as \'tomorrow\' in general speech.' },
    { zh: '后天', pinyin: 'hòu tiān', en: 'the day after tomorrow', note: 'Lit. \'after-heaven-day\'; the day two days ahead.' },
    { zh: '大后天', pinyin: 'dà hòu tiān', en: 'three days from now', note: '大 adds distance to 后天.' },
    { zh: '昨天', pinyin: 'zuó tiān', en: 'yesterday', note: 'Compare 昨 \'yesterday\' vs 今 \'now\'.' },
    { zh: '前天', pinyin: 'qián tiān', en: 'the day before yesterday', note: 'Two days back from today.' },
    { zh: '上个月', pinyin: 'shàng ge yuè', en: 'last month', note: '上 = previous, 个月 = this month\'s counterpart.' },
    { zh: '下个月', pinyin: 'xià ge yuè', en: 'next month', note: '下 = next, on calendars and in speech.' },
    { zh: '这个星期', pinyin: 'zhè ge xīng qī', en: 'this week', note: 'This + measure + noun is the standard time frame.' },
    { zh: '下星期', pinyin: 'xià ge xīng qī', en: 'next week', note: '下星期三 = next Wednesday.' },
    { zh: '上星期', pinyin: 'shàng ge xīng qī', en: 'last week', note: '上星期日 = last Sunday.' },
    { zh: '今年', pinyin: 'jīn nián', en: 'this year', note: 'Often 2026年 = the year 2026.' },
    { zh: '明年', pinyin: 'míng nián', en: 'next year', note: '明 \'bright\' = the next one, as in 明天.' },
    { zh: '去年', pinyin: 'qù nián', en: 'last year', note: 'Used for the previous calendar year.' },
    { zh: '今天几号', pinyin: 'jīn tiān jǐ hào', en: 'What day of the month is today?', note: 'The standard way to ask the date.' },
    { zh: '年月日顺序', pinyin: 'nián yuè rì xù shù', en: 'year – month – day order', note: 'Chinese dates run year → month → day: 2026年10月1日.' },
    { zh: '2026年10月1日', pinyin: 'èr líng èr liù nián shí yuè yī rì', en: 'October 1, 2026 (date order)', note: 'Read year digit by digit; month and day use 月 and 日.' },
  ],
  times: [
    { zh: '现在', pinyin: 'xiàn zài', en: 'now / what time is it', note: '现在几点？ Xiànzài jǐ diǎn? = What time is it now?' },
    { zh: '几点了', pinyin: 'jǐ diǎn le', en: 'What time is it?', note: 'Add 了 once the expected time has passed.' },
    { zh: '什么时候', pinyin: 'shén me shí hóu', en: 'when / at what time', note: 'Used for both past and future time.' },
    { zh: '早上', pinyin: 'zǎo shang', en: 'in the morning', note: '早上七点 = seven in the morning.' },
    { zh: '上午', pinyin: 'shàng wǔ', en: 'morning (before noon)', note: 'Formal register; 上午 9 点.' },
    { zh: '中午', pinyin: 'zhōng wǔ', en: 'noon / midday', note: '中午十二点 = noon; 中 = middle of the day.' },
    { zh: '下午', pinyin: 'xià wǔ', en: 'afternoon', note: '下午三点 = three in the afternoon.' },
    { zh: '傍晚', pinyin: 'bàng wǎn', en: 'dusk / early evening', note: '傍晚 six-ish; 晚 = evening, the partner of 早.' },
    { zh: '晚上', pinyin: 'wǎn shang', en: 'in the evening / at night', note: '晚上八点 = eight at night.' },
    { zh: '夜里', pinyin: 'yè li', en: 'during the night', note: '夜里十二点 = midnight.' },
    { zh: '凌晨', pinyin: 'líng chén', en: 'before dawn', note: '凌晨三点 = three in the early morning.' },
    { zh: '早上 – 中午 – 晚上', pinyin: 'zǎo shang – zhōng wǔ – wǎn shang', en: 'morning – noon – evening', note: 'The three everyday parts of the day.' },
    { zh: '一点', pinyin: 'yī diǎn', en: '1 o\'clock', note: '点 diǎn is the hour; 一点 in the morning = 1 a.m.' },
    { zh: '三点一刻', pinyin: 'sān diǎn yí kè', en: 'quarter past three', note: '一刻 = 15 minutes; 一刻 = a quarter.' },
    { zh: '三点三刻', pinyin: 'sān diǎn sān kè', en: 'quarter to four (45 min)', note: '三刻 = 45 minutes; traditional usage.' },
    { zh: '三点半', pinyin: 'sān diǎn bàn', en: 'half past three', note: '半 = half; the most common way to say :30.' },
    { zh: '一个半小时', pinyin: 'yí ge bàn xiǎo shí', en: 'an hour and a half', note: 'Build it with 1 个 + 半 + 小时.' },
    { zh: '半个小时', pinyin: 'bàn ge xiǎo shí', en: 'half an hour', note: '半个 is the usual form; also 半小时.' },
    { zh: '一刻钟', pinyin: 'yí kè zhōng', en: 'a quarter of an hour', note: '钟 = the bell or clock face; 15 minutes.' },
    { zh: '五点差一刻', pinyin: 'wǔ diǎn chà yí kè', en: 'twelve forty-five (a quarter to five)', note: '差 = short of; used for \'to\' the hour.' },
    { zh: '差十分七点', pinyin: 'chà shí fēn qī diǎn', en: 'twelve fifty (ten to seven)', note: '差 + minutes + hour = \'to the hour\'.' },
    { zh: '十二点', pinyin: 'shí èr diǎn', en: 'twelve o\'clock (noon/midnight)', note: '12:00; 中午十二点 = noon, 晚上十二点 = midnight.' },
    { zh: '现在几点了', pinyin: 'xiàn zài jǐ diǎn le', en: 'What time is it now?', note: 'The polite full form; 几点 alone is casual.' },
    { zh: '八点一刻', pinyin: 'bā diǎn yí kè', en: '8:15 (quarter past eight)', note: 'Same pattern: hour + 点 + 一刻.' },
    { zh: '二十四点', pinyin: 'èr shí sì diǎn', en: '24:00 (midnight, formal)', note: 'Formal and written; speech uses 晚上十二点.' },
    { zh: '时间', pinyin: 'shí jiān', en: 'time', note: 'Lit. \'time person\'; the general noun for time.' },
    { zh: '时候', pinyin: 'shí hóu', en: 'time (a moment)', note: '用在 \'到时候\' = when the time comes.' },
    { zh: '一点钟', pinyin: 'yì diǎn zhōng', en: 'o\'clock', note: '钟 is optional but common in formal speech: 十点钟.' },
  ],
};
