/* MandarinPath vocabulary pack 2 — next-tier everyday vocabulary.
   Loaded as window.MP_WORDS2. Every entry carries a worked example sentence
   built only from HSK 1-2 vocabulary so a beginner can read it. */
window.MP_WORDS2 = [ { zh: "头", pinyin: "tóu", en: "head", hsk: "HSK 1", theme: "body",
    ex_zh: "我的头有一点疼。", ex_pinyin: "Wǒ de tóu yǒu yìdiǎn téng.", ex_en: "My head hurts a little." },
  { zh: "脸", pinyin: "liǎn", en: "face", hsk: "HSK 2", theme: "body",
    ex_zh: "洗完脸，我很高兴。", ex_pinyin: "Xǐ wán liǎn, wǒ hěn gāoxìng.", ex_en: "After washing my face, I feel happy." },
  { zh: "头发", pinyin: "tóufa", en: "hair", hsk: "HSK 3", theme: "body",
    ex_zh: "她的头发很长。", ex_pinyin: "Tā de tóufa hěn cháng.", ex_en: "Her hair is very long." },
  { zh: "耳朵", pinyin: "ěrduo", en: "ear", hsk: "HSK 2", theme: "body",
    ex_zh: "我哥哥的耳朵很大。", ex_pinyin: "Wǒ gēge de ěrduo hěn dà.", ex_en: "My older brother's ears are big." },
  { zh: "鼻子", pinyin: "bízi", en: "nose", hsk: "HSK 2", theme: "body",
    ex_zh: "他的鼻子很小。", ex_pinyin: "Tā de bízi hěn xiǎo.", ex_en: "His nose is small." },
  { zh: "嘴巴", pinyin: "zuǐba", en: "mouth", hsk: "HSK 2", theme: "body",
    ex_zh: "吃饭以前要张开嘴巴。", ex_pinyin: "Chī fàn yǐqián yào zhāngkāi zuǐba.", ex_en: "Open your mouth before you eat." },
  { zh: "脖子", pinyin: "bózi", en: "neck", hsk: "HSK 3", theme: "body",
    ex_zh: "我的脖子有点疼。", ex_pinyin: "Wǒ de bózi yǒudiǎn téng.", ex_en: "My neck hurts a bit." },
  { zh: "肩膀", pinyin: "jiānbǎng", en: "shoulder", hsk: "HSK 4", theme: "body",
    ex_zh: "他肩膀上背着一个包。", ex_pinyin: "Tā jiānbǎng shàng bēi zhe yí ge bāo.", ex_en: "He has a bag on his shoulder." },
  { zh: "胳膊", pinyin: "gēbo", en: "arm", hsk: "HSK 3", theme: "body",
    ex_zh: "她抬起胳膊看手表。", ex_pinyin: "Tā tái qǐ gēbo kàn shǒubiǎo.", ex_en: "She raises her arm to look at her watch." },
  { zh: "手指", pinyin: "shǒuzhǐ", en: "finger", hsk: "HSK 3", theme: "body",
    ex_zh: "他的手指很干净。", ex_pinyin: "Tā de shǒuzhǐ hěn gānjìng.", ex_en: "His fingers are very clean." },
  { zh: "肚子", pinyin: "dùzi", en: "belly; stomach", hsk: "HSK 2", theme: "body",
    ex_zh: "我肚子饿了，想吃饭。", ex_pinyin: "Wǒ dùzi èle, xiǎng chī fàn.", ex_en: "I'm hungry and want to eat." },
  { zh: "腰", pinyin: "yāo", en: "waist; lower back", hsk: "HSK 3", theme: "body",
    ex_zh: "他坐了一天，腰很疼。", ex_pinyin: "Tā zuò le yì tiān, yāo hěn téng.", ex_en: "He sat all day and his back hurts." },
  { zh: "腿", pinyin: "tuǐ", en: "leg", hsk: "HSK 2", theme: "body",
    ex_zh: "我的腿有点酸。", ex_pinyin: "Wǒ de tuǐ yǒudiǎn suān.", ex_en: "My legs feel a bit sore." },
  { zh: "脚", pinyin: "jiǎo", en: "foot", hsk: "HSK 1", theme: "body",
    ex_zh: "我的脚很冷。", ex_pinyin: "Wǒ de jiǎo hěn lěng.", ex_en: "My feet are very cold." },
  { zh: "膝盖", pinyin: "xīgài", en: "knee", hsk: "HSK 4", theme: "body",
    ex_zh: "奶奶的膝盖不好。", ex_pinyin: "Nǎinai de xīgài bù hǎo.", ex_en: "Grandma's knees aren't good." },
  { zh: "牙", pinyin: "yá", en: "tooth", hsk: "HSK 2", theme: "body",
    ex_zh: "早上要刷牙。", ex_pinyin: "Zǎoshang yào shuā yá.", ex_en: "You need to brush your teeth in the morning." },
  { zh: "舌头", pinyin: "shétou", en: "tongue", hsk: "HSK 3", theme: "body",
    ex_zh: "他被烫到舌头了。", ex_pinyin: "Tā bèi tàng dào shétou le.", ex_en: "He burned his tongue." },
  { zh: "皮肤", pinyin: "pífū", en: "skin", hsk: "HSK 4", theme: "body",
    ex_zh: "冬天皮肤很干。", ex_pinyin: "Dōngtiān pífū hěn gān.", ex_en: "Skin gets very dry in winter." },
  { zh: "血", pinyin: "xuè", en: "blood", hsk: "HSK 3", theme: "body",
    ex_zh: "他的手上有很多血。", ex_pinyin: "Tā de shǒu shàng yǒu hěn duō xuè.", ex_en: "There is a lot of blood on his hand." },
  { zh: "汗", pinyin: "hàn", en: "sweat", hsk: "HSK 3", theme: "body",
    ex_zh: "他出了一身汗。", ex_pinyin: "Tā chū le yì shēn hàn.", ex_en: "He sweated all over." },
  { zh: "声音", pinyin: "shēngyīn", en: "voice; sound", hsk: "HSK 2", theme: "body",
    ex_zh: "她的声音很好听。", ex_pinyin: "Tā de shēngyīn hěn hǎotīng.", ex_en: "Her voice is very pleasant." },
  { zh: "身体", pinyin: "shēntǐ", en: "body (health)", hsk: "HSK 3", theme: "health",
    ex_zh: "运动以后身体很好。", ex_pinyin: "Yùndòng yǐhòu shēntǐ hěn hǎo.", ex_en: "Your body feels good after exercise." },
  { zh: "健康", pinyin: "jiànkāng", en: "health (noun)", hsk: "HSK 3", theme: "health",
    ex_zh: "他身体很健康。", ex_pinyin: "Tā shēntǐ hěn jiànkāng.", ex_en: "He is very healthy." },
  { zh: "病", pinyin: "bìng", en: "illness; to be ill", hsk: "HSK 3", theme: "health",
    ex_zh: "他病了，在家休息。", ex_pinyin: "Tā bìng le, zài jiā xiūxi.", ex_en: "He's ill and resting at home." },
  { zh: "疼", pinyin: "téng", en: "to hurt (aching)", hsk: "HSK 3", theme: "health",
    ex_zh: "我的牙很疼。", ex_pinyin: "Wǒ de yá hěn téng.", ex_en: "My tooth hurts a lot." },
  { zh: "咳嗽", pinyin: "késou", en: "to cough", hsk: "HSK 4", theme: "health",
    ex_zh: "他一晚上都在咳嗽。", ex_pinyin: "Tā yí wǎnshàng dōu zài késou.", ex_en: "He coughed all night." },
  { zh: "发烧", pinyin: "fāshāo", en: "to have a fever", hsk: "HSK 4", theme: "health",
    ex_zh: "孩子发烧了，快去医院。", ex_pinyin: "Háizi fāshāo le, kuài qù yīyuàn.", ex_en: "The child has a fever; go to the hospital quickly." },
  { zh: "感冒", pinyin: "gǎnmào", en: "to catch a cold", hsk: "HSK 4", theme: "health",
    ex_zh: "天冷了，容易感冒。", ex_pinyin: "Tiān lěng le, róngyì gǎnmào.", ex_en: "When it's cold it's easy to catch a cold." },
  { zh: "嗓子", pinyin: "sǎngzi", en: "throat; voice", hsk: "HSK 4", theme: "health",
    ex_zh: "我嗓子疼，说不出话。", ex_pinyin: "Wǒ sǎngzi téng, shuō bu chū huà.", ex_en: "My throat hurts and I can't speak." },
  { zh: "休息", pinyin: "xiūxi", en: "to rest; break", hsk: "HSK 3", theme: "health",
    ex_zh: "你累的时候要休息。", ex_pinyin: "Nǐ lèi de shíhou yào xiūxi.", ex_en: "You should rest when you are tired." },
  { zh: "病人", pinyin: "bìngrén", en: "patient; sick person", hsk: "HSK 3", theme: "health",
    ex_zh: "这个病人今天好多了。", ex_pinyin: "Zhège bìngrén jīntiān hǎo duō le.", ex_en: "This patient is much better today." },
  { zh: "打针", pinyin: "dǎzhēn", en: "to get an injection", hsk: "HSK 4", theme: "health",
    ex_zh: "小孩打针的时候很害怕。", ex_pinyin: "Xiǎohái dǎzhēn de shíhou hěn hàipà.", ex_en: "Children are scared when they get an injection." },
  { zh: "吃药", pinyin: "chīyào", en: "to take medicine", hsk: "HSK 3", theme: "health",
    ex_zh: "每天吃药，不要着急。", ex_pinyin: "Měitiān chīyào, bú yào zháojí.", ex_en: "Take your medicine every day; don't worry." },
  { zh: "治疗", pinyin: "zhìliáo", en: "to treat; treatment", hsk: "HSK 4", theme: "health",
    ex_zh: "这个治疗很成功。", ex_pinyin: "Zhège zhìliáo hěn chénggōng.", ex_en: "This treatment was very successful." },
  { zh: "检查", pinyin: "jiǎnchá", en: "to examine; check-up", hsk: "HSK 4", theme: "health",
    ex_zh: "医生给我做了一次检查。", ex_pinyin: "Yīshēng gěi wǒ zuò le yí cì jiǎnchá.", ex_en: "The doctor gave me a check-up." },
  { zh: "体温", pinyin: "tǐwēn", en: "body temperature", hsk: "HSK 4", theme: "health",
    ex_zh: "他的体温太高了。", ex_pinyin: "Tā de tǐwēn tài gāo le.", ex_en: "His body temperature is too high." },
  { zh: "严重", pinyin: "yánzhòng", en: "serious; severe", hsk: "HSK 4", theme: "health",
    ex_zh: "他的病不严重。", ex_pinyin: "Tā de bìng bù yánzhòng.", ex_en: "His illness isn't serious." },
  { zh: "危险", pinyin: "wēixiǎn", en: "dangerous", hsk: "HSK 4", theme: "health",
    ex_zh: "外面很冷，不要出去，太危险了。", ex_pinyin: "Wàimiàn hěn lěng, bú yào chūqù, tài wēixiǎn le.", ex_en: "It's cold outside; don't go out, it's too dangerous." },
  { zh: "房间", pinyin: "fángjiān", en: "room", hsk: "HSK 2", theme: "home",
    ex_zh: "我的房间很小。", ex_pinyin: "Wǒ de fángjiān hěn xiǎo.", ex_en: "My room is very small." },
  { zh: "客厅", pinyin: "kètīng", en: "living room", hsk: "HSK 3", theme: "home",
    ex_zh: "全家人在客厅看电视。", ex_pinyin: "Quán jiā rén zài kètīng kàn diànshì.", ex_en: "The whole family is watching TV in the living room." },
  { zh: "厨房", pinyin: "chúfáng", en: "kitchen", hsk: "HSK 2", theme: "home",
    ex_zh: "妈妈在厨房做饭。", ex_pinyin: "Māma zài chúfáng zuò fàn.", ex_en: "Mom is cooking in the kitchen." },
  { zh: "厕所", pinyin: "cèsuǒ", en: "toilet; restroom", hsk: "HSK 2", theme: "home",
    ex_zh: "厕所在楼的右边。", ex_pinyin: "Cèsuǒ zài lóu de yòubian.", ex_en: "The restroom is on the right side of the building." },
  { zh: "楼", pinyin: "lóu", en: "building; floor", hsk: "HSK 2", theme: "home",
    ex_zh: "我家在五楼。", ex_pinyin: "Wǒ jiā zài wǔ lóu.", ex_en: "My home is on the fifth floor." },
  { zh: "楼下", pinyin: "lóuxià", en: "downstairs", hsk: "HSK 2", theme: "home",
    ex_zh: "他在楼下等我。", ex_pinyin: "Tā zài lóuxià děng wǒ.", ex_en: "He's waiting for me downstairs." },
  { zh: "电梯", pinyin: "diàntī", en: "elevator; lift", hsk: "HSK 3", theme: "home",
    ex_zh: "太高了，我们坐电梯。", ex_pinyin: "Tài gāo le, wǒmen zuò diàntī.", ex_en: "It's too high; let's take the elevator." },
  { zh: "房子", pinyin: "fángzi", en: "house; apartment", hsk: "HSK 2", theme: "home",
    ex_zh: "这房子很新。", ex_pinyin: "Zhè fángzi hěn xīn.", ex_en: "This house is very new." },
  { zh: "窗户", pinyin: "chuānghu", en: "window", hsk: "HSK 2", theme: "home",
    ex_zh: "请把窗户关上。", ex_pinyin: "Qǐng bǎ chuānghu guānshàng.", ex_en: "Please close the window." },
  { zh: "桌子", pinyin: "zhuōzi", en: "table; desk", hsk: "HSK 2", theme: "home",
    ex_zh: "书在桌子上。", ex_pinyin: "Shū zài zhuōzi shàng.", ex_en: "The book is on the table." },
  { zh: "椅子", pinyin: "yǐzi", en: "chair", hsk: "HSK 2", theme: "home",
    ex_zh: "请坐这把椅子。", ex_pinyin: "Qǐng zuò zhè bǎ yǐzi.", ex_en: "Please sit on this chair." },
  { zh: "沙发", pinyin: "shāfā", en: "sofa; couch", hsk: "HSK 4", theme: "home",
    ex_zh: "他在沙发上睡着了。", ex_pinyin: "Tā zài shāfā shàng shuìzháo le.", ex_en: "He fell asleep on the sofa." },
  { zh: "冰箱", pinyin: "bīngxiāng", en: "refrigerator", hsk: "HSK 4", theme: "home",
    ex_zh: "牛奶在冰箱里。", ex_pinyin: "Niúnǎi zài bīngxiāng lǐ.", ex_en: "The milk is in the refrigerator." },
  { zh: "空调", pinyin: "kōngtiáo", en: "air conditioner", hsk: "HSK 4", theme: "home",
    ex_zh: "夏天开空调，很舒服。", ex_pinyin: "Xiàtiān kāi kōngtiáo, hěn shūfu.", ex_en: "We turn on the air conditioner in summer; it's comfortable." },
  { zh: "电视", pinyin: "diànshì", en: "television", hsk: "HSK 3", theme: "home",
    ex_zh: "晚上我们看电视。", ex_pinyin: "Wǎnshàng wǒmen kàn diànshì.", ex_en: "We watch TV in the evening." },
  { zh: "钥匙", pinyin: "yàoshi", en: "key", hsk: "HSK 3", theme: "home",
    ex_zh: "我的钥匙丢了。", ex_pinyin: "Wǒ de yàoshi diū le.", ex_en: "I've lost my key." },
  { zh: "学校", pinyin: "xuéxiào", en: "school", hsk: "HSK 2", theme: "school",
    ex_zh: "我们的学校很大。", ex_pinyin: "Wǒmen de xuéxiào hěn dà.", ex_en: "Our school is very big." },
  { zh: "教室", pinyin: "jiàoshì", en: "classroom", hsk: "HSK 2", theme: "school",
    ex_zh: "教室里有四十个学生。", ex_pinyin: "Jiàoshì lǐ yǒu sìshí ge xuéshēng.", ex_en: "There are forty students in the classroom." },
  { zh: "课本", pinyin: "kèběn", en: "textbook", hsk: "HSK 2", theme: "school",
    ex_zh: "请打开课本。", ex_pinyin: "Qǐng dǎkāi kèběn.", ex_en: "Please open the textbook." },
  { zh: "笔记本", pinyin: "bǐjìběn", en: "notebook", hsk: "HSK 2", theme: "school",
    ex_zh: "我买了一个新笔记本。", ex_pinyin: "Wǒ mǎi le yí ge xīn bǐjìběn.", ex_en: "I bought a new notebook." },
  { zh: "铅笔", pinyin: "qiānbǐ", en: "pencil", hsk: "HSK 2", theme: "school",
    ex_zh: "请给我一支铅笔。", ex_pinyin: "Qǐng gěi wǒ yì zhī qiānbǐ.", ex_en: "Please give me a pencil." },
  { zh: "钢笔", pinyin: "gāngbǐ", en: "fountain pen", hsk: "HSK 3", theme: "school",
    ex_zh: "我用钢笔写字。", ex_pinyin: "Wǒ yòng gāngbǐ xiě zì.", ex_en: "I write with a fountain pen." },
  { zh: "黑板", pinyin: "hēibǎn", en: "blackboard", hsk: "HSK 2", theme: "school",
    ex_zh: "老师写在黑板上。", ex_pinyin: "Lǎoshī xiě zài hēibǎn shàng.", ex_en: "The teacher writes on the blackboard." },
  { zh: "书包", pinyin: "shūbāo", en: "schoolbag; backpack", hsk: "HSK 2", theme: "school",
    ex_zh: "她的书包很漂亮。", ex_pinyin: "Tā de shūbāo hěn piàoliang.", ex_en: "Her schoolbag is very pretty." },
  { zh: "作业", pinyin: "zuòyè", en: "homework", hsk: "HSK 2", theme: "school",
    ex_zh: "我在家做作业。", ex_pinyin: "Wǒ zài jiā zuò zuòyè.", ex_en: "I do my homework at home." },
  { zh: "考试", pinyin: "kǎoshì", en: "exam; test", hsk: "HSK 3", theme: "school",
    ex_zh: "明天我要考试。", ex_pinyin: "Míngtiān wǒ yào kǎoshì.", ex_en: "I have an exam tomorrow." },
  { zh: "办公室", pinyin: "bàngōngshì", en: "office", hsk: "HSK 4", theme: "work",
    ex_zh: "他在办公室上班。", ex_pinyin: "Tā zài bàngōngshì shàngbān.", ex_en: "He works in the office." },
  { zh: "公司", pinyin: "gōngsī", en: "company", hsk: "HSK 2", theme: "work",
    ex_zh: "这家公司很大。", ex_pinyin: "Zhè jiā gōngsī hěn dà.", ex_en: "This company is very big." },
  { zh: "上班", pinyin: "shàngbān", en: "to go to work", hsk: "HSK 3", theme: "work",
    ex_zh: "我每天早上八点上班。", ex_pinyin: "Wǒ měitiān zǎoshang bā diǎn shàngbān.", ex_en: "I start work at eight every morning." },
  { zh: "下班", pinyin: "xiàbān", en: "to get off work", hsk: "HSK 3", theme: "work",
    ex_zh: "他六点下班。", ex_pinyin: "Tā liù diǎn xiàbān.", ex_en: "He gets off work at six." },
  { zh: "同事", pinyin: "tóngshì", en: "colleague", hsk: "HSK 3", theme: "work",
    ex_zh: "我的同事很好。", ex_pinyin: "Wǒ de tóngshì hěn hǎo.", ex_en: "My colleagues are very nice." },
  { zh: "老板", pinyin: "lǎobǎn", en: "boss", hsk: "HSK 3", theme: "work",
    ex_zh: "老板给我们加了工资。", ex_pinyin: "Lǎobǎn gěi wǒmen jiā le gōngzī.", ex_en: "The boss gave us a raise." },
  { zh: "员工", pinyin: "yuángōng", en: "employee; staff member", hsk: "HSK 4", theme: "work",
    ex_zh: "这家公司有五十个员工。", ex_pinyin: "Zhè jiā gōngsī yǒu wǔshí ge yuángōng.", ex_en: "This company has fifty employees." },
  { zh: "经理", pinyin: "jīnglǐ", en: "manager", hsk: "HSK 4", theme: "work",
    ex_zh: "经理今天开会。", ex_pinyin: "Jīnglǐ jīntiān kāihuì.", ex_en: "The manager has a meeting today." },
  { zh: "开会", pinyin: "kāihuì", en: "to hold a meeting", hsk: "HSK 3", theme: "work",
    ex_zh: "我们下午开会。", ex_pinyin: "Wǒmen xiàwǔ kāihuì.", ex_en: "We have a meeting in the afternoon." },
  { zh: "工资", pinyin: "gōngzī", en: "salary; wage", hsk: "HSK 4", theme: "work",
    ex_zh: "我的工资不高。", ex_pinyin: "Wǒ de gōngzī bù gāo.", ex_en: "My salary isn't high." },
  { zh: "邮件", pinyin: "yóujiàn", en: "email", hsk: "HSK 4", theme: "work",
    ex_zh: "我给她发了一封邮件。", ex_pinyin: "Wǒ gěi tā fā le yì fēng yóujiàn.", ex_en: "I sent her an email." },
  { zh: "警察", pinyin: "jǐngchá", en: "police officer", hsk: "HSK 3", theme: "work",
    ex_zh: "警察在马路上。", ex_pinyin: "Jǐngchá zài mǎlù shàng.", ex_en: "The police officer is on the road." },
  { zh: "司机", pinyin: "sījī", en: "driver", hsk: "HSK 3", theme: "work",
    ex_zh: "那个司机很好。", ex_pinyin: "Nà ge sījī hěn hǎo.", ex_en: "That driver is very good." },
  { zh: "厨师", pinyin: "chúshī", en: "cook; chef", hsk: "HSK 4", theme: "work",
    ex_zh: "这家饭店的厨师很有名。", ex_pinyin: "Zhè jiā fàndiǎn de chúshī hěn yǒumíng.", ex_en: "This restaurant's chef is famous." },
  { zh: "工程师", pinyin: "gōngchéngshī", en: "engineer", hsk: "HSK 4", theme: "work",
    ex_zh: "姐姐是一名工程师。", ex_pinyin: "Jiějie shì yì míng gōngchéngshī.", ex_en: "My older sister is an engineer." },
  { zh: "公园", pinyin: "gōngyuán", en: "park", hsk: "HSK 2", theme: "places",
    ex_zh: "我们常去公园。", ex_pinyin: "Wǒmen cháng qù gōngyuán.", ex_en: "We often go to the park." },
  { zh: "花园", pinyin: "huāyuán", en: "flower garden", hsk: "HSK 3", theme: "places",
    ex_zh: "花园里有很多花。", ex_pinyin: "Huāyuán lǐ yǒu hěn duō huā.", ex_en: "There are many flowers in the garden." },
  { zh: "广场", pinyin: "guǎngchǎng", en: "square; plaza", hsk: "HSK 4", theme: "places",
    ex_zh: "广场上有很多人。", ex_pinyin: "Guǎngchǎng shàng yǒu hěn duō rén.", ex_en: "There are many people on the square." },
  { zh: "博物馆", pinyin: "bówùguǎn", en: "museum", hsk: "HSK 3", theme: "places",
    ex_zh: "我们去博物馆。", ex_pinyin: "Wǒmen qù bówùguǎn.", ex_en: "Let's go to the museum." },
  { zh: "图书馆", pinyin: "túshūguǎn", en: "library", hsk: "HSK 3", theme: "places",
    ex_zh: "我在图书馆学中文。", ex_pinyin: "Wǒ zài túshūguǎn xué Zhōngwén.", ex_en: "I study Chinese at the library." },
  { zh: "菜市场", pinyin: "càishìchǎng", en: "vegetable market", hsk: "HSK 4", theme: "places",
    ex_zh: "妈妈常去菜市场。", ex_pinyin: "Māma cháng qù càishìchǎng.", ex_en: "Mom often goes to the vegetable market." },
  { zh: "市场", pinyin: "shìchǎng", en: "market", hsk: "HSK 3", theme: "places",
    ex_zh: "这个市场很热闹。", ex_pinyin: "Zhège shìchǎng hěn rènao.", ex_en: "This market is very lively." },
  { zh: "城市", pinyin: "chéngshì", en: "city", hsk: "HSK 3", theme: "places",
    ex_zh: "这是一个大城市。", ex_pinyin: "Zhè shì yí ge dà chéngshì.", ex_en: "This is a big city." },
  { zh: "街区", pinyin: "jiēqū", en: "neighborhood; block", hsk: "HSK 4", theme: "places",
    ex_zh: "这个街区很安静。", ex_pinyin: "Zhège jiēqū hěn ānjìng.", ex_en: "This neighborhood is very quiet." },
  { zh: "走廊", pinyin: "zǒuláng", en: "hallway; corridor", hsk: "HSK 3", theme: "places",
    ex_zh: "厕所在走廊的右边。", ex_pinyin: "Cèsuǒ zài zǒuláng de yòubian.", ex_en: "The restroom is on the right of the hallway." },
  { zh: "车站", pinyin: "chēzhàn", en: "station", hsk: "HSK 3", theme: "transport",
    ex_zh: "车站在学校对面。", ex_pinyin: "Chēzhàn zài xuéxiào duìmiàn.", ex_en: "The station is across from the school." },
  { zh: "火车", pinyin: "huǒchē", en: "train", hsk: "HSK 2", theme: "transport",
    ex_zh: "我们要坐火车去北京。", ex_pinyin: "Wǒmen yào zuò huǒchē qù Běijīng.", ex_en: "We're taking a train to Beijing." },
  { zh: "公交车", pinyin: "gōngjiāochē", en: "bus", hsk: "HSK 2", theme: "transport",
    ex_zh: "我坐公交车去上班。", ex_pinyin: "Wǒ zuò gōngjiāochē qù shàngbān.", ex_en: "I take the bus to work." },
  { zh: "自行车", pinyin: "zìxíngchē", en: "bicycle", hsk: "HSK 2", theme: "transport",
    ex_zh: "他骑自行车上班。", ex_pinyin: "Tā qí zìxíngchē shàngbān.", ex_en: "He rides his bike to work." },
  { zh: "走路", pinyin: "zǒulù", en: "to walk", hsk: "HSK 2", theme: "transport",
    ex_zh: "从这里走路十分钟。", ex_pinyin: "Cóng zhèlǐ zǒulù shí fēnzhōng.", ex_en: "It's a ten-minute walk from here." },
  { zh: "开车", pinyin: "kāichē", en: "to drive", hsk: "HSK 3", theme: "transport",
    ex_zh: "他每天开车上班。", ex_pinyin: "Tā měitiān kāichē shàngbān.", ex_en: "He drives to work every day." },
  { zh: "红绿灯", pinyin: "hónglǜdēng", en: "traffic light", hsk: "HSK 3", theme: "transport",
    ex_zh: "过马路要看红绿灯。", ex_pinyin: "Guò mǎlù yào kàn hóng lǜ dēng.", ex_en: "Look at the traffic light when you cross the road." },
  { zh: "马路", pinyin: "mǎlù", en: "road; street", hsk: "HSK 2", theme: "transport",
    ex_zh: "新马路上车很多。", ex_pinyin: "Xīn mǎlù shàng chē hěn duō.", ex_en: "There are many cars on the new road." },
  { zh: "排队", pinyin: "páiduì", en: "to queue; line up", hsk: "HSK 4", theme: "transport",
    ex_zh: "请在这里排队。", ex_pinyin: "Qǐng zài zhèlǐ páiduì.", ex_en: "Please line up here." },
  { zh: "刷卡", pinyin: "shuākǎ", en: "to swipe a card", hsk: "HSK 4", theme: "transport",
    ex_zh: "上公交车要刷卡。", ex_pinyin: "Shàng gōngjiāochē yào shuākǎ.", ex_en: "You need to swipe your card when you get on the bus." },
  { zh: "米饭", pinyin: "mǐfàn", en: "rice", hsk: "HSK 2", theme: "food",
    ex_zh: "我最爱吃米饭。", ex_pinyin: "Wǒ zuì ài chī mǐfàn.", ex_en: "I love eating rice." },
  { zh: "面条", pinyin: "miàntiáo", en: "noodles", hsk: "HSK 2", theme: "food",
    ex_zh: "晚上我们吃面条。", ex_pinyin: "Wǎnshàng wǒmen chī miàntiáo.", ex_en: "We eat noodles in the evening." },
  { zh: "饺子", pinyin: "jiǎozi", en: "dumpling", hsk: "HSK 2", theme: "food",
    ex_zh: "过年的时候包饺子。", ex_pinyin: "Guònián de shíhou bāo jiǎozi.", ex_en: "We make dumplings at New Year." },
  { zh: "包子", pinyin: "bāozi", en: "steamed bun", hsk: "HSK 2", theme: "food",
    ex_zh: "早饭我买两个包子。", ex_pinyin: "Zǎofàn wǒ mǎi liǎng ge bāozi.", ex_en: "For breakfast I buy two buns." },
  { zh: "面包", pinyin: "miànbāo", en: "bread", hsk: "HSK 2", theme: "food",
    ex_zh: "我爱吃新鲜面包。", ex_pinyin: "Wǒ ài chī xīnxiān miànbāo.", ex_en: "I like eating fresh bread." },
  { zh: "鸡蛋", pinyin: "jīdàn", en: "egg", hsk: "HSK 2", theme: "food",
    ex_zh: "妈妈每天煮一个鸡蛋。", ex_pinyin: "Māma měitiān zhǔ yí ge jīdàn.", ex_en: "Mom cooks one egg every day." },
  { zh: "汤", pinyin: "tāng", en: "soup", hsk: "HSK 3", theme: "food",
    ex_zh: "这碗汤很热。", ex_pinyin: "Zhè wǎn tāng hěn rè.", ex_en: "This bowl of soup is very hot." },
  { zh: "粥", pinyin: "zhōu", en: "congee; rice porridge", hsk: "HSK 3", theme: "food",
    ex_zh: "早上喝粥很舒服。", ex_pinyin: "Zǎoshang hē zhōu hěn shūfu.", ex_en: "Drinking congee in the morning feels good." },
  { zh: "水果", pinyin: "shuǐguǒ", en: "fruit", hsk: "HSK 2", theme: "food",
    ex_zh: "多吃水果对身体好。", ex_pinyin: "Duō chī shuǐguǒ duì shēntǐ hǎo.", ex_en: "Eating more fruit is good for your health." },
  { zh: "苹果", pinyin: "píngguǒ", en: "apple", hsk: "HSK 2", theme: "food",
    ex_zh: "这个苹果很甜。", ex_pinyin: "Zhège píngguǒ hěn tián.", ex_en: "This apple is very sweet." },
  { zh: "香蕉", pinyin: "xiāngjiāo", en: "banana", hsk: "HSK 2", theme: "food",
    ex_zh: "我喜欢吃香蕉。", ex_pinyin: "Wǒ xǐhuan chī xiāngjiāo.", ex_en: "I like eating bananas." },
  { zh: "西瓜", pinyin: "xīguā", en: "watermelon", hsk: "HSK 2", theme: "food",
    ex_zh: "夏天吃西瓜很凉快。", ex_pinyin: "Xiàtiān chī xīguā hěn liángkuai.", ex_en: "Eating watermelon in summer is refreshing." },
  { zh: "葡萄", pinyin: "pútao", en: "grapes", hsk: "HSK 2", theme: "food",
    ex_zh: "一串葡萄很贵。", ex_pinyin: "Yí chuàn pútao hěn guì.", ex_en: "A bunch of grapes is expensive." },
  { zh: "草莓", pinyin: "cǎoméi", en: "strawberry", hsk: "HSK 3", theme: "food",
    ex_zh: "草莓在春天最好吃。", ex_pinyin: "Cǎoméi zài chūntiān zuì hǎochī.", ex_en: "Strawberries taste best in spring." },
  { zh: "橘子", pinyin: "júzi", en: "tangerine; orange", hsk: "HSK 2", theme: "food",
    ex_zh: "他剥了一个橘子。", ex_pinyin: "Tā bō le yí ge júzi.", ex_en: "He peeled a tangerine." },
  { zh: "蔬菜", pinyin: "shūcài", en: "vegetable", hsk: "HSK 3", theme: "food",
    ex_zh: "妈妈买了许多蔬菜。", ex_pinyin: "Māma mǎi le xǔduō shūcài.", ex_en: "Mom bought a lot of vegetables." },
  { zh: "土豆", pinyin: "tǔdòu", en: "potato", hsk: "HSK 2", theme: "food",
    ex_zh: "我喜欢土豆做的菜。", ex_pinyin: "Wǒ xǐhuan tǔdòu zuò de cài.", ex_en: "I like dishes made with potatoes." },
  { zh: "鸡蛋汤", pinyin: "jīdàntāng", en: "egg soup", hsk: "HSK 3", theme: "food",
    ex_zh: "生病的时候喝鸡蛋汤。", ex_pinyin: "Shēng bìng de shíhou hē jīdàntāng.", ex_en: "When you're ill you drink egg soup." },
  { zh: "糖", pinyin: "táng", en: "sugar; candy", hsk: "HSK 3", theme: "food",
    ex_zh: "咖啡里不加糖。", ex_pinyin: "Kāfēi lǐ bù jiā táng.", ex_en: "No sugar in the coffee." },
  { zh: "盐", pinyin: "yán", en: "salt", hsk: "HSK 4", theme: "food",
    ex_zh: "这个菜有点咸，盐多了。", ex_pinyin: "Zhège cài yǒudiǎn xián, yán duō le.", ex_en: "This dish is a bit salty; there's too much salt." },
  { zh: "醋", pinyin: "cù", en: "vinegar", hsk: "HSK 4", theme: "food",
    ex_zh: "吃饺子要放一点醋。", ex_pinyin: "Chī jiǎozi yào fàng yìdiǎn cù.", ex_en: "Add a little vinegar when you eat dumplings." },
  { zh: "辣", pinyin: "là", en: "spicy; hot (flavor)", hsk: "HSK 3", theme: "food",
    ex_zh: "四川菜很辣。", ex_pinyin: "Sìchuān cài hěn là.", ex_en: "Sichuan food is very spicy." },
  { zh: "甜", pinyin: "tián", en: "sweet", hsk: "HSK 3", theme: "food",
    ex_zh: "这个蛋糕太甜了。", ex_pinyin: "Zhège dàngāo tài tián le.", ex_en: "This cake is too sweet." },
  { zh: "味道", pinyin: "wèidào", en: "taste; flavor", hsk: "HSK 3", theme: "food",
    ex_zh: "这家饭店的味道很好。", ex_pinyin: "Zhè jiā fàndiǎn de wèidào hěn hǎo.", ex_en: "This restaurant tastes very good." },
  { zh: "牛奶", pinyin: "niúnǎi", en: "milk", hsk: "HSK 2", theme: "drink",
    ex_zh: "我每天早上喝牛奶。", ex_pinyin: "Wǒ měitiān zǎoshang hē niúnǎi.", ex_en: "I drink milk every morning." },
  { zh: "啤酒", pinyin: "píjiǔ", en: "beer", hsk: "HSK 3", theme: "drink",
    ex_zh: "晚上他喝啤酒。", ex_pinyin: "Wǎnshàng tā hē píjiǔ.", ex_en: "He drinks beer in the evening." },
  { zh: "果汁", pinyin: "guǒzhī", en: "juice", hsk: "HSK 2", theme: "drink",
    ex_zh: "早餐我喝果汁。", ex_pinyin: "Zǎocān wǒ hē guǒzhī.", ex_en: "I drink juice at breakfast." },
  { zh: "开水", pinyin: "kāishuǐ", en: "boiling water", hsk: "HSK 3", theme: "drink",
    ex_zh: "喝开水身体好。", ex_pinyin: "Hē kāishuǐ shēntǐ hǎo.", ex_en: "Drinking boiled water is good for you." },
  { zh: "矿泉水", pinyin: "kuàngquánshuǐ", en: "mineral water", hsk: "HSK 3", theme: "drink",
    ex_zh: "我喜欢喝矿泉水。", ex_pinyin: "Wǒ xǐhuan hē kuàngquánshuǐ.", ex_en: "I like drinking mineral water." },
  { zh: "红茶", pinyin: "hóngchá", en: "black tea", hsk: "HSK 4", theme: "drink",
    ex_zh: "红茶很好喝。", ex_pinyin: "Hóngchá hěn hǎohē.", ex_en: "Black tea tastes good." },
  { zh: "蛋糕", pinyin: "dàngāo", en: "cake", hsk: "HSK 3", theme: "food",
    ex_zh: "生日的时候我们吃蛋糕。", ex_pinyin: "Shēngrì de shíhou wǒmen chī dàngāo.", ex_en: "We eat cake on birthdays." },
  { zh: "衣服", pinyin: "yīfu", en: "clothes", hsk: "HSK 2", theme: "clothing",
    ex_zh: "天冷了，多穿点衣服。", ex_pinyin: "Tiān lěng le, duō chuān diǎn yīfu.", ex_en: "It's cold; wear more clothes." },
  { zh: "裤子", pinyin: "kùzi", en: "trousers; pants", hsk: "HSK 2", theme: "clothing",
    ex_zh: "这条裤子很便宜。", ex_pinyin: "Zhè tiáo kùzi hěn piányi.", ex_en: "These trousers are cheap." },
  { zh: "裙子", pinyin: "qúnzi", en: "skirt; dress", hsk: "HSK 2", theme: "clothing",
    ex_zh: "她穿一条新裙子。", ex_pinyin: "Tā chuān yì tiáo xīn qúnzi.", ex_en: "She's wearing a new skirt." },
  { zh: "外套", pinyin: "wàitào", en: "coat; jacket", hsk: "HSK 3", theme: "clothing",
    ex_zh: "出门要穿外套。", ex_pinyin: "Chūmén yào chuān wàitào.", ex_en: "Wear a coat when you go out." },
  { zh: "毛衣", pinyin: "máoyī", en: "sweater", hsk: "HSK 2", theme: "clothing",
    ex_zh: "冬天我穿毛衣。", ex_pinyin: "Dōngtiān wǒ chuān máoyī.", ex_en: "I wear a sweater in winter." },
  { zh: "衬衫", pinyin: "chénshān", en: "shirt", hsk: "HSK 4", theme: "clothing",
    ex_zh: "他的衬衫很白。", ex_pinyin: "Tā de chénshān hěn bái.", ex_en: "His shirt is very white." },
  { zh: "鞋", pinyin: "xié", en: "shoes", hsk: "HSK 2", theme: "clothing",
    ex_zh: "我买了新鞋。", ex_pinyin: "Wǒ mǎi le xīn xié.", ex_en: "I bought new shoes." },
  { zh: "帽子", pinyin: "màozi", en: "hat; cap", hsk: "HSK 2", theme: "clothing",
    ex_zh: "戴帽子很暖和。", ex_pinyin: "Dài màozi hěn nuǎnhuo.", ex_en: "Wearing a hat keeps you warm." },
  { zh: "袜子", pinyin: "wàzi", en: "socks", hsk: "HSK 3", theme: "clothing",
    ex_zh: "我的袜子不见了。", ex_pinyin: "Wǒ de wàzi bú jiàn le.", ex_en: "My socks are missing." },
  { zh: "围巾", pinyin: "wéijīn", en: "scarf", hsk: "HSK 4", theme: "clothing",
    ex_zh: "她的围巾是红色的。", ex_pinyin: "Tā de wéijīn shì hóngsè de.", ex_en: "Her scarf is red." },
  { zh: "眼镜", pinyin: "yǎnjìng", en: "glasses", hsk: "HSK 2", theme: "clothing",
    ex_zh: "爸爸戴眼镜。", ex_pinyin: "Bàba dài yǎnjìng.", ex_en: "Dad wears glasses." },
  { zh: "灰色", pinyin: "huīsè", en: "grey; gray", hsk: "HSK 3", theme: "colors",
    ex_zh: "今天天空是灰色的。", ex_pinyin: "Jīntiān tiānkōng shì huīsè de.", ex_en: "The sky is grey today." },
  { zh: "紫色", pinyin: "zǐsè", en: "purple", hsk: "HSK 3", theme: "colors",
    ex_zh: "她喜欢紫色的花。", ex_pinyin: "Tā xǐhuan zǐsè de huā.", ex_en: "She likes purple flowers." },
  { zh: "橙色", pinyin: "chéngsè", en: "orange (color)", hsk: "HSK 3", theme: "colors",
    ex_zh: "橙子本来就是橙色。", ex_pinyin: "Chéngzi běnlái jiù shì chéngsè.", ex_en: "Oranges are orange in color." },
  { zh: "粉色", pinyin: "fěnsè", en: "pink", hsk: "HSK 3", theme: "colors",
    ex_zh: "她房间是粉色的。", ex_pinyin: "Tā fángjiān shì fěnsè de.", ex_en: "Her room is pink." },
  { zh: "颜色", pinyin: "yánsè", en: "color", hsk: "HSK 2", theme: "colors",
    ex_zh: "这个书包什么颜色？", ex_pinyin: "Zhège shūbāo shénme yánsè?", ex_en: "What color is this schoolbag?" },
  { zh: "猫", pinyin: "māo", en: "cat", hsk: "HSK 2", theme: "animals",
    ex_zh: "我家有一只猫。", ex_pinyin: "Wǒ jiā yǒu yì zhī māo.", ex_en: "We have a cat at home." },
  { zh: "狗", pinyin: "gǒu", en: "dog", hsk: "HSK 2", theme: "animals",
    ex_zh: "那只狗很小。", ex_pinyin: "Nà zhī gǒu hěn xiǎo.", ex_en: "That dog is very small." },
  { zh: "鸟", pinyin: "niǎo", en: "bird", hsk: "HSK 2", theme: "animals",
    ex_zh: "公园里有很多鸟。", ex_pinyin: "Gōngyuán lǐ yǒu hěn duō niǎo.", ex_en: "There are many birds in the park." },
  { zh: "鱼", pinyin: "yú", en: "fish", hsk: "HSK 2", theme: "animals",
    ex_zh: "我们吃鱼。", ex_pinyin: "Wǒmen chī yú.", ex_en: "We eat fish." },
  { zh: "猪", pinyin: "zhū", en: "pig", hsk: "HSK 2", theme: "animals",
    ex_zh: "农场里有很多猪。", ex_pinyin: "Nóngchǎng lǐ yǒu hěn duō zhū.", ex_en: "There are many pigs on the farm." },
  { zh: "羊", pinyin: "yáng", en: "sheep; goat", hsk: "HSK 2", theme: "animals",
    ex_zh: "山上有很多羊。", ex_pinyin: "Shān shàng yǒu hěn duō yáng.", ex_en: "There are many sheep on the hill." },
  { zh: "牛", pinyin: "niú", en: "cow; ox", hsk: "HSK 2", theme: "animals",
    ex_zh: "牛在吃草。", ex_pinyin: "Niú zài chī cǎo.", ex_en: "The cow is eating grass." },
  { zh: "鸡", pinyin: "jī", en: "chicken", hsk: "HSK 2", theme: "animals",
    ex_zh: "早上鸡叫了。", ex_pinyin: "Zǎoshang jī jiào le.", ex_en: "The chicken called in the morning." },
  { zh: "兔子", pinyin: "tùzi", en: "rabbit; bunny", hsk: "HSK 2", theme: "animals",
    ex_zh: "这只兔子很可爱。", ex_pinyin: "Zhè zhī tù zi hěn kě ài.", ex_en: "This rabbit is very cute." },
  { zh: "熊猫", pinyin: "xióngmāo", en: "panda", hsk: "HSK 3", theme: "animals",
    ex_zh: "大熊猫只住在中国。", ex_pinyin: "Dà xióngmāo zhǐ zhù zài Zhōngguó.", ex_en: "Giant pandas live only in China." },
  { zh: "老虎", pinyin: "lǎohǔ", en: "tiger", hsk: "HSK 3", theme: "animals",
    ex_zh: "老虎是很大的动物。", ex_pinyin: "Lǎohǔ shì hěn dà de dòngwù.", ex_en: "A tiger is a big animal." },
  { zh: "猴子", pinyin: "hóuzi", en: "monkey", hsk: "HSK 3", theme: "animals",
    ex_zh: "猴子喜欢吃香蕉。", ex_pinyin: "Hóuzi xǐhuan chī xiāngjiāo.", ex_en: "Monkeys like eating bananas." },
  { zh: "天气", pinyin: "tiānqì", en: "weather", hsk: "HSK 3", theme: "weather",
    ex_zh: "今天的天气很好。", ex_pinyin: "Jīntiān de tiānqì hěn hǎo.", ex_en: "The weather is very nice today." },
  { zh: "下雨", pinyin: "xiàyǔ", en: "to rain", hsk: "HSK 2", theme: "weather",
    ex_zh: "外面在下雨。", ex_pinyin: "Wàimiàn zài xiàyǔ.", ex_en: "It's raining outside." },
  { zh: "太阳", pinyin: "tàiyáng", en: "sun", hsk: "HSK 2", theme: "weather",
    ex_zh: "今天太阳很大。", ex_pinyin: "Jīntiān tàiyáng hěn dà.", ex_en: "The sun is strong today." },
  { zh: "月亮", pinyin: "yuèliang", en: "moon", hsk: "HSK 2", theme: "weather",
    ex_zh: "今晚月亮很亮。", ex_pinyin: "Jīntiān yuèliang hěn liàng.", ex_en: "The moon is very bright tonight." },
  { zh: "云", pinyin: "yún", en: "cloud", hsk: "HSK 3", theme: "weather",
    ex_zh: "天上有很多云。", ex_pinyin: "Tiān shàng yǒu hěn duō yún.", ex_en: "There are many clouds in the sky." },
  { zh: "风", pinyin: "fēng", en: "wind", hsk: "HSK 2", theme: "weather",
    ex_zh: "风很大。", ex_pinyin: "Fēng hěn dà.", ex_en: "The wind is strong." },
  { zh: "雨伞", pinyin: "yǔsǎn", en: "umbrella", hsk: "HSK 2", theme: "weather",
    ex_zh: "出门带一把雨伞。", ex_pinyin: "Chūmén dài yì bǎ yǔsǎn.", ex_en: "Take an umbrella when you go out." },
  { zh: "冬天", pinyin: "dōngtiān", en: "winter", hsk: "HSK 2", theme: "time",
    ex_zh: "冬天很冷。", ex_pinyin: "Dōngtiān hěn lěng.", ex_en: "Winter is cold." },
  { zh: "春天", pinyin: "chūntiān", en: "spring (season)", hsk: "HSK 2", theme: "time",
    ex_zh: "春天花都开了。", ex_pinyin: "Chūntiān huā dōu kāi le.", ex_en: "In spring all the flowers bloom." },
  { zh: "夏天", pinyin: "xiàtiān", en: "summer", hsk: "HSK 2", theme: "time",
    ex_zh: "夏天我们去海边。", ex_pinyin: "Xiàtiān wǒmen qù hǎibiān.", ex_en: "In summer we go to the sea." },
  { zh: "秋天", pinyin: "qiūtiān", en: "autumn; fall", hsk: "HSK 2", theme: "time",
    ex_zh: "秋天的北京很好看。", ex_pinyin: "Qiūtiān de Běijīng hěn hǎokàn.", ex_en: "Beijing looks beautiful in autumn." },
  { zh: "星期", pinyin: "xīngqī", en: "week; day of the week", hsk: "HSK 2", theme: "time",
    ex_zh: "星期一我要上班。", ex_pinyin: "Xīngqīyī wǒ yào shàngbān.", ex_en: "I have to work on Monday." },
  { zh: "周末", pinyin: "zhōumò", en: "weekend", hsk: "HSK 2", theme: "time",
    ex_zh: "周末我们去公园。", ex_pinyin: "Zhōumò wǒmen qù gōngyuán.", ex_en: "We go to the park on the weekend." },
  { zh: "小时", pinyin: "xiǎoshí", en: "hour", hsk: "HSK 2", theme: "time",
    ex_zh: "我等了你两个小时。", ex_pinyin: "Wǒ děng le nǐ liǎng ge xiǎoshí.", ex_en: "I waited for you for two hours." },
  { zh: "生日", pinyin: "shēngrì", en: "birthday", hsk: "HSK 2", theme: "time",
    ex_zh: "今天是我的生日。", ex_pinyin: "Jīntiān shì wǒ de shēngrì.", ex_en: "Today is my birthday." },
  { zh: "去年", pinyin: "qùnián", en: "last year", hsk: "HSK 3", theme: "time",
    ex_zh: "去年我去过北京。", ex_pinyin: "Qùnián wǒ qù guo Běijīng.", ex_en: "Last year I went to Beijing." },
  { zh: "马上", pinyin: "mǎshàng", en: "right away", hsk: "HSK 2", theme: "time",
    ex_zh: "我马上就来。", ex_pinyin: "Wǒ mǎshàng jiù lái.", ex_en: "I'll come right away." },
  { zh: "已经", pinyin: "yǐjīng", en: "already", hsk: "HSK 2", theme: "time",
    ex_zh: "我已经吃过了。", ex_pinyin: "Wǒ yǐjīng chī guo le.", ex_en: "I've already eaten." },
  { zh: "每天", pinyin: "měitiān", en: "every day", hsk: "HSK 1", theme: "time",
    ex_zh: "我每天走路上学。", ex_pinyin: "Wǒ měitiān zǒulù shàngxué.", ex_en: "I walk to school every day." },
  { zh: "哥哥", pinyin: "gēge", en: "older brother", hsk: "HSK 2", theme: "family",
    ex_zh: "我哥哥在大学工作。", ex_pinyin: "Wǒ gēge zài dàxué gōngzuò.", ex_en: "My older brother works at a university." },
  { zh: "姐姐", pinyin: "jiějie", en: "older sister", hsk: "HSK 2", theme: "family",
    ex_zh: "姐姐比我大三岁。", ex_pinyin: "Jiějie bǐ wǒ dà sān suì.", ex_en: "My sister is three years older than me." },
  { zh: "弟弟", pinyin: "dìdi", en: "younger brother", hsk: "HSK 2", theme: "family",
    ex_zh: "弟弟还在上小学。", ex_pinyin: "Dìdi hái zài shàng xiǎoxué.", ex_en: "My younger brother is still in primary school." },
  { zh: "妹妹", pinyin: "mèimei", en: "younger sister", hsk: "HSK 2", theme: "family",
    ex_zh: "妹妹七岁了。", ex_pinyin: "Mèimei qī suì le.", ex_en: "My younger sister is seven years old." },
  { zh: "爷爷", pinyin: "yéye", en: "grandfather (paternal)", hsk: "HSK 2", theme: "family",
    ex_zh: "爷爷今年八十岁了。", ex_pinyin: "Yéye jīntiān bāshí suì le.", ex_en: "Grandpa is eighty years old this year." },
  { zh: "奶奶", pinyin: "nǎinai", en: "grandmother (paternal)", hsk: "HSK 2", theme: "family",
    ex_zh: "奶奶在公园里。", ex_pinyin: "Nǎinai zài gōngyuán lǐ.", ex_en: "Grandma is in the park." },
  { zh: "孩子", pinyin: "háizi", en: "child", hsk: "HSK 2", theme: "family",
    ex_zh: "这个孩子很聪明。", ex_pinyin: "Zhège háizi hěn cōngming.", ex_en: "This child is very smart." },
  { zh: "男人", pinyin: "nánrén", en: "man; adult male", hsk: "HSK 2", theme: "people",
    ex_zh: "那个男人很高。", ex_pinyin: "Nà ge nánrén hěn gāo.", ex_en: "That man is very tall." },
  { zh: "女人", pinyin: "nǚrén", en: "woman; adult female", hsk: "HSK 2", theme: "people",
    ex_zh: "那个女人是老师。", ex_pinyin: "Nà ge nǚrén shì lǎoshī.", ex_en: "That woman is a teacher." },
  { zh: "老人", pinyin: "lǎorén", en: "old person; elder", hsk: "HSK 2", theme: "people",
    ex_zh: "公园里有很多老人。", ex_pinyin: "Gōngyuán lǐ yǒu hěn duō lǎorén.", ex_en: "There are many old people in the park." },
  { zh: "客人", pinyin: "kèrén", en: "guest; visitor", hsk: "HSK 3", theme: "people",
    ex_zh: "今天家里来了客人。", ex_pinyin: "Jīntiān jiā lǐ lái le kèrén.", ex_en: "A guest came to our home today." },
  { zh: "邻居", pinyin: "línjū", en: "neighbor", hsk: "HSK 3", theme: "people",
    ex_zh: "我的邻居会做中国菜。", ex_pinyin: "Wǒ de línjū huì zuò Zhōngguó cài.", ex_en: "My neighbor can cook Chinese food." },
  { zh: "元", pinyin: "yuán", en: "yuan (currency unit)", hsk: "HSK 3", theme: "money",
    ex_zh: "这本书二十八元。", ex_pinyin: "Zhè běn shū èrshíbā yuán.", ex_en: "This book is twenty-eight yuan." },
  { zh: "块", pinyin: "kuài", en: "yuan (colloquial)", hsk: "HSK 3", theme: "money",
    ex_zh: "一杯咖啡三十块。", ex_pinyin: "Yì bēi kāfēi sānshí kuài.", ex_en: "A cup of coffee is thirty yuan." },
  { zh: "现金", pinyin: "xiànjīn", en: "cash", hsk: "HSK 4", theme: "money",
    ex_zh: "这个店不收现金。", ex_pinyin: "Zhège diàn bù shōu xiànjīn.", ex_en: "This shop doesn't take cash." },
  { zh: "银行卡", pinyin: "yínhángkǎ", en: "bank card", hsk: "HSK 4", theme: "money",
    ex_zh: "我用银行卡付钱。", ex_pinyin: "Wǒ yòng yínhángkǎ fù qián.", ex_en: "I pay with my bank card." },
  { zh: "存钱", pinyin: "cúnqián", en: "to save money", hsk: "HSK 3", theme: "money",
    ex_zh: "每个月我都存钱。", ex_pinyin: "Měi ge yuè wǒ dōu cúnqián.", ex_en: "I save money every month." },
  { zh: "取钱", pinyin: "qǔqián", en: "to withdraw money", hsk: "HSK 4", theme: "money",
    ex_zh: "我要在银行取钱。", ex_pinyin: "Wǒ yào zài yínháng qǔqián.", ex_en: "I need to withdraw money at the bank." },
  { zh: "价格", pinyin: "jiàgé", en: "price", hsk: "HSK 4", theme: "shopping",
    ex_zh: "这个价格很合理。", ex_pinyin: "Zhège jiàgé hěn hélǐ.", ex_en: "This price is very reasonable." },
  { zh: "便宜", pinyin: "piányi", en: "cheap", hsk: "HSK 2", theme: "shopping",
    ex_zh: "这里的菜很便宜。", ex_pinyin: "Zhèlǐ de cài hěn piányi.", ex_en: "The food here is very cheap." },
  { zh: "打折", pinyin: "dǎzhé", en: "on sale; discounted", hsk: "HSK 4", theme: "shopping",
    ex_zh: "今天打折，很便宜。", ex_pinyin: "Jīntiān dǎzhé, hěn piányi.", ex_en: "It's on sale today; it's cheap." },
  { zh: "收据", pinyin: "shōujù", en: "receipt", hsk: "HSK 4", theme: "shopping",
    ex_zh: "请给我收据。", ex_pinyin: "Qǐng gěi wǒ shōujù.", ex_en: "Please give me the receipt." },
  { zh: "换", pinyin: "huàn", en: "to exchange; to change", hsk: "HSK 2", theme: "shopping",
    ex_zh: "这个太小了，我能换一个吗？", ex_pinyin: "Zhège tài xiǎo le, wǒ néng huàn yí ge ma?", ex_en: "This is too small; can I exchange it?" },
  { zh: "尺子", pinyin: "chǐzi", en: "ruler", hsk: "HSK 3", theme: "shopping",
    ex_zh: "用尺子量一量。", ex_pinyin: "Yòng chǐzi liáng yi liang.", ex_en: "Measure it with a ruler." },
  { zh: "闹钟", pinyin: "nàozhōng", en: "alarm clock", hsk: "HSK 4", theme: "home",
    ex_zh: "闹钟响了，我起床。", ex_pinyin: "Nàozhōng xiǎng le, wǒ qǐchuáng.", ex_en: "The alarm rang and I got up." },
  { zh: "电脑", pinyin: "diànnǎo", en: "computer", hsk: "HSK 3", theme: "technology",
    ex_zh: "我在电脑上学习。", ex_pinyin: "Wǒ zài diànnǎo shàng xuéxí.", ex_en: "I study on the computer." },
  { zh: "电话", pinyin: "diànhuà", en: "telephone; call", hsk: "HSK 2", theme: "technology",
    ex_zh: "我给他打个电话。", ex_pinyin: "Wǒ gěi tā dǎ ge diànhuà.", ex_en: "I'll give him a call." },
  { zh: "软件", pinyin: "ruǎnjiàn", en: "software", hsk: "HSK 4", theme: "technology",
    ex_zh: "这个软件很好用。", ex_pinyin: "Zhège ruǎnjiàn hěn hǎoyòng.", ex_en: "This software is very useful." },
  { zh: "网络", pinyin: "wǎngluò", en: "internet; network", hsk: "HSK 3", theme: "technology",
    ex_zh: "家里网络很好。", ex_pinyin: "Jiā lǐ wǎngluò hěn hǎo.", ex_en: "The internet at home is good." },
  { zh: "照片", pinyin: "zhàopiān", en: "photo; picture", hsk: "HSK 3", theme: "technology",
    ex_zh: "这张照片很好看。", ex_pinyin: "Zhè zhāng zhàopiān hěn hǎokàn.", ex_en: "This photo is very nice." },
  { zh: "密码", pinyin: "mìmǎ", en: "password; code", hsk: "HSK 4", theme: "technology",
    ex_zh: "请记住密码。", ex_pinyin: "Qǐng jìzhù mìmǎ.", ex_en: "Please remember the password." },
  { zh: "高兴", pinyin: "gāoxìng", en: "happy; glad", hsk: "HSK 2", theme: "feelings",
    ex_zh: "收到礼物我很高兴。", ex_pinyin: "Shōudào lǐwù wǒ hěn gāoxìng.", ex_en: "I'm very happy to get the gift." },
  { zh: "快乐", pinyin: "kuàilè", en: "happy; joyful", hsk: "HSK 2", theme: "feelings",
    ex_zh: "祝你生日快乐。", ex_pinyin: "Zhù nǐ shēngrì kuàilè.", ex_en: "Happy birthday to you." },
  { zh: "难过", pinyin: "nánguò", en: "sad; to feel sad", hsk: "HSK 3", theme: "feelings",
    ex_zh: "他今天很难过。", ex_pinyin: "Tā jīntiān hěn nánguò.", ex_en: "He feels very sad today." },
  { zh: "生气", pinyin: "shēngqì", en: "angry", hsk: "HSK 2", theme: "feelings",
    ex_zh: "别生气，没关系。", ex_pinyin: "Bié shēngqì, méiguānxi.", ex_en: "Don't be angry; it's okay." },
  { zh: "害怕", pinyin: "hàipà", en: "afraid; scared", hsk: "HSK 3", theme: "feelings",
    ex_zh: "我有点害怕。", ex_pinyin: "Wǒ yǒudiǎn hàipà.", ex_en: "I'm a little afraid." },
  { zh: "紧张", pinyin: "jǐnzhāng", en: "nervous; tense", hsk: "HSK 4", theme: "feelings",
    ex_zh: "考试的时候我很紧张。", ex_pinyin: "Kǎoshì de shíhou wǒ hěn jǐnzhāng.", ex_en: "I get very nervous during exams." },
  { zh: "着急", pinyin: "zháojí", en: "anxious; in a hurry", hsk: "HSK 4", theme: "feelings",
    ex_zh: "别着急，慢慢来。", ex_pinyin: "Bié zháojí, mànmàn lái.", ex_en: "Don't worry; take your time." },
  { zh: "担心", pinyin: "dānxīn", en: "to worry about", hsk: "HSK 3", theme: "feelings",
    ex_zh: "妈妈很担心我。", ex_pinyin: "Māma hěn dānxīn wǒ.", ex_en: "Mom worries about me." },
  { zh: "失望", pinyin: "shīwàng", en: "disappointed", hsk: "HSK 4", theme: "feelings",
    ex_zh: "他很失望。", ex_pinyin: "Tā hěn shīwàng.", ex_en: "He is very disappointed." },
  { zh: "安静", pinyin: "ānjìng", en: "quiet; calm", hsk: "HSK 3", theme: "feelings",
    ex_zh: "这里很安静。", ex_pinyin: "Zhèlǐ hěn ānjìng.", ex_en: "It's very quiet here." },
  { zh: "热闹", pinyin: "rènao", en: "lively; bustling", hsk: "HSK 4", theme: "feelings",
    ex_zh: "街上很热闹。", ex_pinyin: "Jiē shàng hěn rènao.", ex_en: "The street is very lively." },
  { zh: "幸福", pinyin: "xìngfú", en: "happy; blissful", hsk: "HSK 3", theme: "feelings",
    ex_zh: "我们很幸福。", ex_pinyin: "Wǒmen hěn xìngfú.", ex_en: "We are very happy." },
  { zh: "饿", pinyin: "è", en: "hungry", hsk: "HSK 3", theme: "feelings",
    ex_zh: "我很饿，我们去吃饭。", ex_pinyin: "Wǒ hěn è, wǒmen qù chī fàn.", ex_en: "I'm hungry; let's go eat." },
  { zh: "渴", pinyin: "kě", en: "thirsty", hsk: "HSK 3", theme: "feelings",
    ex_zh: "我渴了，想喝水。", ex_pinyin: "Wǒ kě le, xiǎng hē shuǐ.", ex_en: "I'm thirsty; I want water." },
  { zh: "困", pinyin: "kùn", en: "sleepy", hsk: "HSK 3", theme: "feelings",
    ex_zh: "我很困，要睡觉了。", ex_pinyin: "Wǒ hěn kùn, yào shuìjiào le.", ex_en: "I'm sleepy; I need to sleep." },
  { zh: "住", pinyin: "zhù", en: "to live; to stay", hsk: "HSK 2", theme: "verbs",
    ex_zh: "我住在北京。", ex_pinyin: "Wǒ zhù zài Běijīng.", ex_en: "I live in Beijing." },
  { zh: "睡", pinyin: "shuì", en: "to sleep", hsk: "HSK 2", theme: "verbs",
    ex_zh: "孩子睡着了。", ex_pinyin: "Háizi shuìzháo le.", ex_en: "The child fell asleep." },
  { zh: "起床", pinyin: "qǐchuáng", en: "to get up", hsk: "HSK 2", theme: "verbs",
    ex_zh: "我七点起床。", ex_pinyin: "Wǒ qī diǎn qǐchuáng.", ex_en: "I get up at seven." },
  { zh: "洗澡", pinyin: "xǐzǎo", en: "to take a shower", hsk: "HSK 2", theme: "verbs",
    ex_zh: "晚上要洗澡。", ex_pinyin: "Wǎnshàng yào xǐzǎo.", ex_en: "I take a shower in the evening." },
  { zh: "刷牙", pinyin: "shuāyá", en: "to brush one's teeth", hsk: "HSK 2", theme: "verbs",
    ex_zh: "睡觉以前要刷牙。", ex_pinyin: "Shuìjiào yǐqián yào shuāyá.", ex_en: "Brush your teeth before bed." },
  { zh: "穿", pinyin: "chuān", en: "to wear", hsk: "HSK 2", theme: "verbs",
    ex_zh: "他穿一件白衣服。", ex_pinyin: "Tā chuān yí jiàn bái yīfu.", ex_en: "He's wearing a white shirt." },
  { zh: "做", pinyin: "zuò", en: "to make; to do", hsk: "HSK 1", theme: "verbs",
    ex_zh: "妈妈做饭，我洗碗。", ex_pinyin: "Māma zuò fàn, wǒ xǐ wǎn.", ex_en: "Mom cooks and I wash the dishes." },
  { zh: "洗", pinyin: "xǐ", en: "to wash", hsk: "HSK 2", theme: "verbs",
    ex_zh: "请洗手。", ex_pinyin: "Qǐng xǐ shǒu.", ex_en: "Please wash your hands." },
  { zh: "打扫", pinyin: "dǎsǎo", en: "to clean (a room)", hsk: "HSK 4", theme: "verbs",
    ex_zh: "我每天打扫房间。", ex_pinyin: "Wǒ měitiān dǎsǎo fángjiān.", ex_en: "I clean my room every day." },
  { zh: "修理", pinyin: "xiūlǐ", en: "to repair", hsk: "HSK 4", theme: "verbs",
    ex_zh: "他修理自行车。", ex_pinyin: "Tā xiūlǐ zìxíngchē.", ex_en: "He repairs bicycles." },
  { zh: "借", pinyin: "jiè", en: "to borrow; to lend", hsk: "HSK 2", theme: "verbs",
    ex_zh: "请借我一本书。", ex_pinyin: "Qǐng jiè wǒ yì běn shū.", ex_en: "Please lend me a book." },
  { zh: "听", pinyin: "tīng", en: "to listen", hsk: "HSK 1", theme: "verbs",
    ex_zh: "我在听音乐。", ex_pinyin: "Wǒ zài tīng yīnyuè.", ex_en: "I'm listening to music." },
  { zh: "读", pinyin: "dú", en: "to read aloud", hsk: "HSK 2", theme: "verbs",
    ex_zh: "请你读一遍。", ex_pinyin: "Qǐng nǐ dú yí biàn.", ex_en: "Please read it once." },
  { zh: "写", pinyin: "xiě", en: "to write", hsk: "HSK 1", theme: "verbs",
    ex_zh: "我在本子上写汉字。", ex_pinyin: "Wǒ zài běnzi shàng xiě hànzì.", ex_en: "I'm writing Chinese characters in my notebook." },
  { zh: "记", pinyin: "jì", en: "to remember", hsk: "HSK 3", theme: "verbs",
    ex_zh: "我记不住这个词。", ex_pinyin: "Wǒ jì bu zhù zhège cí.", ex_en: "I can't remember this word." },
  { zh: "忘", pinyin: "wàng", en: "to forget", hsk: "HSK 3", theme: "verbs",
    ex_zh: "我忘了他叫什么。", ex_pinyin: "Wǒ wàng le tā jiào shénme.", ex_en: "I forgot what his name is." },
  { zh: "告诉", pinyin: "gàosu", en: "to tell", hsk: "HSK 3", theme: "verbs",
    ex_zh: "请告诉我你的名字。", ex_pinyin: "Qǐng gàosu wǒ nǐ de míngzi.", ex_en: "Please tell me your name." },
  { zh: "回答", pinyin: "huídá", en: "to answer", hsk: "HSK 3", theme: "verbs",
    ex_zh: "我回答他的问题。", ex_pinyin: "Wǒ huídá tā de wèntí.", ex_en: "I answered his question." },
  { zh: "开始", pinyin: "kāishǐ", en: "to begin", hsk: "HSK 3", theme: "verbs",
    ex_zh: "课开始了。", ex_pinyin: "Kè kāishǐ le.", ex_en: "The class has begun." },
  { zh: "结束", pinyin: "jiéshù", en: "to end; to finish", hsk: "HSK 4", theme: "verbs",
    ex_zh: "会议结束了。", ex_pinyin: "Huìyì jié shù le.", ex_en: "The meeting is over." },
  { zh: "带", pinyin: "dài", en: "to bring; to take (along)", hsk: "HSK 2", theme: "verbs",
    ex_zh: "我带了一把伞。", ex_pinyin: "Wǒ dài le yì bǎ sǎn.", ex_en: "I brought an umbrella." },
  { zh: "放", pinyin: "fàng", en: "to put; to place", hsk: "HSK 2", theme: "verbs",
    ex_zh: "把书放在桌子上。", ex_pinyin: "Bǎ shū fàng zài zhuōzi shàng.", ex_en: "Put the book on the table." },
  { zh: "拿", pinyin: "ná", en: "to take; to hold", hsk: "HSK 2", theme: "verbs",
    ex_zh: "请拿一个苹果。", ex_pinyin: "Qǐng ná yí ge píngguǒ.", ex_en: "Please take an apple." },
  { zh: "走", pinyin: "zǒu", en: "to walk; to go", hsk: "HSK 1", theme: "verbs",
    ex_zh: "我们走吧。", ex_pinyin: "Wǒmen zǒu ba.", ex_en: "Let's go." },
  { zh: "跑", pinyin: "pǎo", en: "to run", hsk: "HSK 2", theme: "verbs",
    ex_zh: "他跑得很快。", ex_pinyin: "Tā pǎo de hěn kuài.", ex_en: "He runs very fast." },
  { zh: "跳", pinyin: "tiào", en: "to jump; to skip", hsk: "HSK 2", theme: "verbs",
    ex_zh: "孩子们在草地上跳。", ex_pinyin: "Háizimen zài cǎodì shàng tiào.", ex_en: "The children are jumping on the grass." },
  { zh: "唱", pinyin: "chàng", en: "to sing", hsk: "HSK 2", theme: "verbs",
    ex_zh: "她唱歌很好听。", ex_pinyin: "Tā chàng gē hěn hǎotīng.", ex_en: "She sings beautifully." },
  { zh: "付款", pinyin: "fùkuǎn", en: "to pay", hsk: "HSK 4", theme: "shopping",
    ex_zh: "在这里付款。", ex_pinyin: "Zài zhèlǐ fùkuǎn.", ex_en: "Pay here." },
  { zh: "送", pinyin: "sòng", en: "to deliver; to give (a gift)", hsk: "HSK 3", theme: "shopping",
    ex_zh: "他们送货到家。", ex_pinyin: "Tāmen sòng huò dào jiā.", ex_en: "They deliver to your home." },
  { zh: "试", pinyin: "shì", en: "to try (on)", hsk: "HSK 3", theme: "shopping",
    ex_zh: "可以试穿吗？", ex_pinyin: "Kěyǐ shìchuān ma?", ex_en: "Can I try it on?" },
  { zh: "选", pinyin: "xuǎn", en: "to choose", hsk: "HSK 3", theme: "shopping",
    ex_zh: "你自己选吧。", ex_pinyin: "Nǐ zìjǐ xuǎn ba.", ex_en: "Choose it yourself." },
  { zh: "顾客", pinyin: "gùkè", en: "customer", hsk: "HSK 4", theme: "shopping",
    ex_zh: "顾客很多，店很忙。", ex_pinyin: "Gùkè hěn duō, diàn hěn máng.", ex_en: "There are many customers, so the shop is busy." },
  { zh: "很", pinyin: "hěn", en: "very", hsk: "HSK 1", theme: "adverbs",
    ex_zh: "这本书很有意思。", ex_pinyin: "Zhè běn shū hěn yǒu yìsi.", ex_en: "This book is very interesting." },
  { zh: "非常", pinyin: "fēicháng", en: "extremely; very", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "他非常高兴。", ex_pinyin: "Tā fēicháng gāoxìng.", ex_en: "He is extremely happy." },
  { zh: "有点", pinyin: "yǒudiǎn", en: "a little; somewhat", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "我有点累。", ex_pinyin: "Wǒ yǒudiǎn lèi.", ex_en: "I'm a little tired." },
  { zh: "比较", pinyin: "bǐjiào", en: "rather; comparatively", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "这个价格比较便宜。", ex_pinyin: "Zhège jiàgé bǐjiào piányi.", ex_en: "This price is fairly cheap." },
  { zh: "总是", pinyin: "zǒngshì", en: "always", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "他总是很忙。", ex_pinyin: "Tā zǒngshì hěn máng.", ex_en: "He is always very busy." },
  { zh: "常常", pinyin: "chángcháng", en: "often; frequently", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "我们常常一起吃饭。", ex_pinyin: "Wǒmen chángcháng yìqǐ chī fàn.", ex_en: "We often eat together." },
  { zh: "经常", pinyin: "jīngcháng", en: "often", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "他经常去图书馆。", ex_pinyin: "Tā jīngcháng qù túshūguǎn.", ex_en: "He often goes to the library." },
  { zh: "有时候", pinyin: "yǒushíhou", en: "sometimes", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "有时候我坐地铁。", ex_pinyin: "Yǒushíhou wǒ zuò dìtiě.", ex_en: "Sometimes I take the subway." },
  { zh: "大概", pinyin: "dàgài", en: "about; roughly", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "大概十分钟就到。", ex_pinyin: "Dàgài shí fēnzhōng jiù dào.", ex_en: "It takes about ten minutes." },
  { zh: "差不多", pinyin: "chàbuduō", en: "almost; nearly", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "作业差不多做完了。", ex_pinyin: "Zuòyè chàbuduō zuò wán le.", ex_en: "The homework is nearly finished." },
  { zh: "一定", pinyin: "yídìng", en: "definitely; must", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "你一定要来。", ex_pinyin: "Nǐ yídìng yào lái.", ex_en: "You definitely have to come." },
  { zh: "当然", pinyin: "dāngrán", en: "of course", hsk: "HSK 3", theme: "adverbs",
    ex_zh: "当然可以。", ex_pinyin: "Dāngrán kěyǐ.", ex_en: "Of course." },
  { zh: "其实", pinyin: "qíshí", en: "actually; in fact", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "其实我很喜欢。", ex_pinyin: "Qíshí wǒ hěn xǐhuan.", ex_en: "Actually, I like it a lot." },
  { zh: "突然", pinyin: "tūrán", en: "suddenly", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "他突然就走了。", ex_pinyin: "Tā tūrán jiù zǒu le.", ex_en: "He suddenly left." },
  { zh: "慢慢", pinyin: "mànmàn", en: "slowly", hsk: "HSK 2", theme: "adverbs",
    ex_zh: "请慢慢说。", ex_pinyin: "Qǐng mànmàn shuō.", ex_en: "Please speak slowly." },
  { zh: "快点", pinyin: "kuài diǎn", en: "faster; hurry up", hsk: "HSK 2", theme: "adverbs",
    ex_zh: "快点，车要开了。", ex_pinyin: "Kuài diǎn, chē yào kāi le.", ex_en: "Hurry up; the car is leaving." },
  { zh: "价钱", pinyin: "jiàqián", en: "price; cost", hsk: "HSK 3", theme: "shopping",
    ex_zh: "这个店的价钱不高。", ex_pinyin: "Zhège diàn de jiàqián bù gāo.", ex_en: "The prices at this shop aren't high." },
  { zh: "找钱", pinyin: "zhǎoqián", en: "to give change", hsk: "HSK 3", theme: "shopping",
    ex_zh: "请给我找钱。", ex_pinyin: "Qǐng gěi wǒ zhǎoqián.", ex_en: "Please give me my change." },
  { zh: "本子", pinyin: "běnzi", en: "notebook; exercise book", hsk: "HSK 2", theme: "school",
    ex_zh: "我在本子上写字。", ex_pinyin: "Wǒ zài běnzi shàng xiě zì.", ex_en: "I'm writing in my notebook." },
  { zh: "下课", pinyin: "xiàkè", en: "class is over", hsk: "HSK 3", theme: "school",
    ex_zh: "下课了，我们去操场。", ex_pinyin: "Xiàkè le, wǒmen qù cāochǎng.", ex_en: "Class is over; let's go to the playground." },
  { zh: "年级", pinyin: "niánjí", en: "grade; year level", hsk: "HSK 3", theme: "school",
    ex_zh: "他读三年级。", ex_pinyin: "Tā dú sān niánjí.", ex_en: "He is in third grade." },
  { zh: "笔记", pinyin: "bǐjì", en: "lecture notes", hsk: "HSK 3", theme: "school",
    ex_zh: "我把笔记借给你。", ex_pinyin: "Wǒ bǎ bǐjì jiè gěi nǐ.", ex_en: "I'll lend you my notes." },
  { zh: "文凭", pinyin: "wénpíng", en: "diploma; certificate", hsk: "HSK 4", theme: "work",
    ex_zh: "他有一张大学文凭。", ex_pinyin: "Tā yǒu yì zhāng dàxué wénpíng.", ex_en: "He has a university diploma." },
  { zh: "工作日", pinyin: "gōngzuò rì", en: "workday; weekday", hsk: "HSK 3", theme: "work",
    ex_zh: "工作日他很忙。", ex_pinyin: "Gōngzuò rì tā hěn máng.", ex_en: "He's busy on weekdays." },
  { zh: "面试", pinyin: "miànshì", en: "job interview", hsk: "HSK 4", theme: "work",
    ex_zh: "明天他有一个面试。", ex_pinyin: "Míngtiān tā yǒu yí ge miànshì.", ex_en: "He has a job interview tomorrow." },
  { zh: "地址", pinyin: "dìzhǐ", en: "address", hsk: "HSK 4", theme: "places",
    ex_zh: "请写上你的地址。", ex_pinyin: "Qǐng xiě shàng nǐ de dìzhǐ.", ex_en: "Please write down your address." },
  { zh: "国家", pinyin: "guójiā", en: "country", hsk: "HSK 3", theme: "places",
    ex_zh: "中国是一个很大的国家。", ex_pinyin: "Zhōngguó shì yí ge hěn dà de guójiā.", ex_en: "China is a very big country." },
  { zh: "北边", pinyin: "běibian", en: "the north side", hsk: "HSK 3", theme: "places",
    ex_zh: "公园在学校的北边。", ex_pinyin: "Gōngyuán zài xuéxiào de běibian.", ex_en: "The park is north of the school." },
  { zh: "桥", pinyin: "qiáo", en: "bridge", hsk: "HSK 3", theme: "places",
    ex_zh: "河上有一座桥。", ex_pinyin: "Hé shàng yǒu yí zuò qiáo.", ex_en: "There is a bridge over the river." },
  { zh: "河边", pinyin: "hébiān", en: "riverside", hsk: "HSK 3", theme: "places",
    ex_zh: "河边有很多树。", ex_pinyin: "Hébiān yǒu hěn duō shù.", ex_en: "There are many trees by the river." },
  { zh: "衣服店", pinyin: "yīfu diàn", en: "clothing store", hsk: "HSK 3", theme: "places",
    ex_zh: "前面有一家衣服店。", ex_pinyin: "Qiánmiàn yǒu yì jiā yīfu diàn.", ex_en: "There's a clothing store ahead." },
  { zh: "咖啡馆", pinyin: "kāfēiguǎn", en: "cafe", hsk: "HSK 4", theme: "places",
    ex_zh: "我们在咖啡馆学习。", ex_pinyin: "Wǒmen zài kāfēiguǎn xuéxí.", ex_en: "We study in the cafe." },
  { zh: "硬币", pinyin: "yìngbì", en: "coin", hsk: "HSK 4", theme: "money",
    ex_zh: "我口袋里有很多硬币。", ex_pinyin: "Wǒ kǒudài lǐ yǒu hěn duō yìngbì.", ex_en: "I have many coins in my pocket." },
  { zh: "钱包", pinyin: "qiánbāo", en: "wallet", hsk: "HSK 3", theme: "money",
    ex_zh: "我的钱包在包里。", ex_pinyin: "Wǒ de qiánbāo zài bāo lǐ.", ex_en: "My wallet is in the bag." },
  { zh: "品质", pinyin: "pǐnzhì", en: "quality", hsk: "HSK 4", theme: "shopping",
    ex_zh: "这个店的品质很好。", ex_pinyin: "Zhège diàn de pǐnzhì hěn hǎo.", ex_en: "The quality in this shop is very good." },
  { zh: "网", pinyin: "wǎng", en: "net; web", hsk: "HSK 3", theme: "technology",
    ex_zh: "我用网看新闻。", ex_pinyin: "Wǒ yòng wǎng kàn xīnwén.", ex_en: "I use the web to read news." },
  { zh: "键盘", pinyin: "jiànpán", en: "keyboard", hsk: "HSK 4", theme: "technology",
    ex_zh: "这个键盘坏了。", ex_pinyin: "Zhège jiànpán huài le.", ex_en: "This keyboard is broken." },
  { zh: "急救包", pinyin: "jíjiù bāo", en: "first-aid kit", hsk: "HSK 4", theme: "health",
    ex_zh: "家里应该有一个急救包。", ex_pinyin: "Jiā lǐ yīnggāi yǒu yí ge jíjiù bāo.", ex_en: "There should be a first-aid kit at home." },
  { zh: "小毛病", pinyin: "xiǎo máobìng", en: "a minor ailment", hsk: "HSK 4", theme: "health",
    ex_zh: "这只是小毛病。", ex_pinyin: "Zhè zhǐshì xiǎo máobìng.", ex_en: "This is only a minor ailment." },
  { zh: "保养", pinyin: "bǎoyǎng", en: "to maintain; take care of", hsk: "HSK 4", theme: "health",
    ex_zh: "每天保养身体很重要。", ex_pinyin: "Měitiān bǎoyǎng shēntǐ hěn zhòngyào.", ex_en: "Taking care of your health every day is important." },
  { zh: "形容", pinyin: "xíngróng", en: "to describe; to call", hsk: "HSK 4", theme: "verbs",
    ex_zh: "我用中文形容一下。", ex_pinyin: "Wǒ yòng Zhōngwén xíngróng yíxià.", ex_en: "Let me describe it in Chinese." },
  { zh: "反复", pinyin: "fǎnfù", en: "repeatedly; over and over", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "他反复说了三次。", ex_pinyin: "Tā fǎnfù shuō le sān cì.", ex_en: "He said it three times." },
  { zh: "顺便", pinyin: "shùnbiàn", en: "conveniently; while I'm at it", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "你去商店的时候顺便买牛奶。", ex_pinyin: "Nǐ qù shāngdiàn de shíhou shùnbiàn mǎi niúnǎi.", ex_en: "Buy milk when you go to the shop." },
  { zh: "恰好", pinyin: "qiàhǎo", en: "just right; exactly", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "我恰好在家。", ex_pinyin: "Wǒ qiàhǎo zài jiā.", ex_en: "I happen to be at home." },
  { zh: "难道", pinyin: "nándào", en: "could it be that", hsk: "HSK 4", theme: "adverbs",
    ex_zh: "难道你不认识他吗？", ex_pinyin: "Nándào nǐ bú rènshi tā ma?", ex_en: "Could it be that you don't know him?" },
  { zh: "亲戚", pinyin: "qīnqi", en: "relatives", hsk: "HSK 3", theme: "family",
    ex_zh: "过年我们去看亲戚。", ex_pinyin: "Guònián wǒmen qù kàn qīnqi.", ex_en: "At New Year we visit our relatives." },
  { zh: "家族", pinyin: "jiāzú", en: "family; clan", hsk: "HSK 4", theme: "family",
    ex_zh: "我们家族很大。", ex_pinyin: "Wǒmen jiāzú hěn dà.", ex_en: "Our family clan is very big." },
  { zh: "夫妻", pinyin: "fūqī", en: "married couple", hsk: "HSK 4", theme: "family",
    ex_zh: "他们是很好的夫妻。", ex_pinyin: "Tāmen shì hěn hǎo de fūqī.", ex_en: "They are a good married couple." },
  { zh: "手提包", pinyin: "shǒutíbāo", en: "handbag", hsk: "HSK 4", theme: "clothing",
    ex_zh: "她买了一个新手提包。", ex_pinyin: "Tā mǎi le yí ge xīn shǒutíbāo.", ex_en: "She bought a new handbag." },
  { zh: "洗发水", pinyin: "xǐfàshuǐ", en: "shampoo", hsk: "HSK 4", theme: "health",
    ex_zh: "洗澡以后要用洗发水。", ex_pinyin: "Xǐzǎo yǐhòu yào yòng xǐfàshuǐ.", ex_en: "Use shampoo after a shower." },
  { zh: "手表", pinyin: "shǒu biǎo", en: "watch", hsk: "HSK 3", theme: "time",
    ex_zh: "我的手表快了三分钟。", ex_pinyin: "Wǒ de shǒu biǎo kuài le sān fēnzhōng.", ex_en: "My watch is three minutes fast." },
  { zh: "闹钟响", pinyin: "nàozhōng xiǎng", en: "the alarm goes off", hsk: "HSK 3", theme: "time",
    ex_zh: "闹钟响了，该起床了。", ex_pinyin: "Nàozhōng xiǎng le, gāi qǐchuáng le.", ex_en: "The alarm rang; time to get up." },
  { zh: "床头", pinyin: "chuángtóu", en: "head of the bed", hsk: "HSK 3", theme: "home",
    ex_zh: "我的书在床头。", ex_pinyin: "Wǒ de shū zài chuángtóu.", ex_en: "My book is at the head of the bed." },
  { zh: "厨房台", pinyin: "chúfáng tái", en: "kitchen counter", hsk: "HSK 4", theme: "home",
    ex_zh: "厨房台上放着水果。", ex_pinyin: "Chúfáng tái shàng fàng zhe shuǐguǒ.", ex_en: "There's fruit on the kitchen counter." },
  { zh: "电话号码", pinyin: "diànhuà hàomǎ", en: "phone number", hsk: "HSK 3", theme: "technology",
    ex_zh: "请写你的电话号码。", ex_pinyin: "Qǐng xiě nǐ de diànhuà hàomǎ.", ex_en: "Please write your phone number." },
  { zh: "地铁口", pinyin: "dìtiě kǒu", en: "subway entrance", hsk: "HSK 3", theme: "transport",
    ex_zh: "地铁口在前面。", ex_pinyin: "Dìtiě kǒu zài qiánmiàn.", ex_en: "The subway entrance is ahead." },
  { zh: "出租车司机", pinyin: "chūzūchē sījī", en: "taxi driver", hsk: "HSK 3", theme: "transport",
    ex_zh: "出租车司机很客气。", ex_pinyin: "Chūzūchē sījī hěn kèqi.", ex_en: "The taxi driver is very polite." },
  { zh: "堵车", pinyin: "dǔchē", en: "traffic jam", hsk: "HSK 4", theme: "transport",
    ex_zh: "早上堵车很严重。", ex_pinyin: "Zǎoshang dǔchē hěn yánzhòng.", ex_en: "There's a bad traffic jam in the morning." },
  { zh: "走路慢", pinyin: "zǒulù màn", en: "to walk slowly", hsk: "HSK 2", theme: "transport",
    ex_zh: "老人走路慢。", ex_pinyin: "Lǎorén zǒulù màn.", ex_en: "Old people walk slowly." },
  { zh: "工作服", pinyin: "gōngzuòfú", en: "work clothes; uniform", hsk: "HSK 4", theme: "work",
    ex_zh: "上班要穿工作服。", ex_pinyin: "Shàngbān yào chuān gōngzuòfú.", ex_en: "You wear work clothes to work." },
  { zh: "下班后", pinyin: "xiàbān hòu", en: "after work", hsk: "HSK 2", theme: "work",
    ex_zh: "下班后我去买菜。", ex_pinyin: "Xiàbān hòu wǒ qù mǎi cài.", ex_en: "After work I go buy vegetables." }
];
